cashubtc/cdk

- crates/cashu-sdk/src/client/blocking.rs
> fix: clippy

- crates/cashu-sdk/src/mint.rs
- crates/cashu-sdk/src/wallet.rs
- crates/cashu/src/nuts/nut00.rs
> improve: handle not enough change outputs provided

- crates/cashu-sdk/src/client/gloo_client.rs
- crates/cashu-sdk/src/client/minreq_client.rs
- crates/cashu-sdk/src/client/mod.rs
- crates/cashu-sdk/src/mint/mod.rs
- crates/cashu-sdk/src/wallet/mod.rs
- crates/cashu/src/nuts/mod.rs
- crates/cashu/src/nuts/nut00.rs
- crates/cashu/src/nuts/nut07.rs
https://github.com/cashubtc/nuts/pull/71
> refactor: nut-07 state

- crates/cashu/src/nuts/nut04.rs
- crates/cashu/src/nuts/nut05.rs
- crates/cashu/src/nuts/nut06.rs
implement https://github.com/cashubtc/nuts/pull/82
closes #60
> feat(nut04/nut05): mint and melt settings as objects

- crates/cashu-sdk/src/client/gloo_client.rs
- crates/cashu-sdk/src/client/minreq_client.rs
- crates/cashu-sdk/src/client/mod.rs
- crates/cashu-sdk/src/mint/localstore/memory.rs
- crates/cashu-sdk/src/mint/localstore/mod.rs
- crates/cashu-sdk/src/mint/localstore/redb_store.rs
- crates/cashu-sdk/src/mint/mod.rs
- crates/cashu-sdk/src/wallet/mod.rs
- crates/cashu/src/nuts/nut07.rs
implement https://github.com/cashubtc/nuts/pull/93
closes #58
> feat(nut07): check state on y

- .config/semgrep.yaml
- flake.nix
> chore: flake fixes

- CODE_STYLE.md
- crates/cashu-sdk/src/mint/localstore/redb_store.rs
- crates/cashu-sdk/src/wallet/localstore/redb_store.rs
- crates/cashu/src/dhke.rs
- crates/cashu/src/nuts/nut01/mod.rs
- rustfmt.toml
Add code style from https://github.com/rust-nostr/nostr/blob/master/CODE_STYLE.md
There are certainty violations of this that will need to be found and fixed.
> chore: add code style and rust fmt

- crates/cdk/src/wallet.rs
> Add refresh mint keys and remove unwraps in wallet

- bindings/cdk-js/src/nuts/nut11.rs
- crates/cdk/src/nuts/mod.rs
- crates/cdk/src/nuts/nut01/mod.rs
- crates/cdk/src/nuts/nut01/public_key.rs
- crates/cdk/src/nuts/nut01/secret_key.rs
- crates/cdk/src/nuts/nut11/mod.rs
- crates/cdk/src/wallet.rs
> refactor: remove nut11 key types

- bindings/cdk-js/src/wallet.rs
- crates/cdk-redb/src/wallet.rs
- crates/cdk-rexie/src/wallet.rs
- crates/cdk/src/cdk_database/mod.rs
- crates/cdk/src/cdk_database/wallet_memory.rs
- crates/cdk/src/mint.rs
- crates/cdk/src/types.rs
- crates/cdk/src/wallet.rs
> feat: check mint quotes

- crates/cdk/src/cdk_database/mint_memory.rs
- crates/cdk/src/cdk_database/wallet_memory.rs
> replace Mutex with Rwlocks in memory DBs

- bindings/cdk-js/src/nuts/nut04.rs
- bindings/cdk-js/src/nuts/nut07.rs
- bindings/cdk-js/src/wallet.rs
- crates/cdk-redb/Cargo.toml
- crates/cdk-redb/src/error.rs
- crates/cdk-redb/src/wallet.rs
- crates/cdk-rexie/src/wallet.rs
- crates/cdk/src/amount.rs
- crates/cdk/src/cdk_database/mod.rs
- crates/cdk/src/cdk_database/wallet_memory.rs
- crates/cdk/src/mint.rs
- crates/cdk/src/nuts/nut00.rs
- crates/cdk/src/nuts/nut04.rs
- crates/cdk/src/nuts/nut07.rs
- crates/cdk/src/nuts/nut11/mod.rs
- crates/cdk/src/nuts/nut13.rs
- crates/cdk/src/types.rs
- crates/cdk/src/util/mod.rs
- crates/cdk/src/wallet.rs
https://github.com/cashubtc/cdk/pull/145 should be merged first since will need to be able to get proofs by condition.
> feat: mint with spending conditions

- bindings/cdk-js/src/nuts/nut04.rs
- bindings/cdk-js/src/nuts/nut07.rs
- bindings/cdk-js/src/wallet.rs
- crates/cdk-redb/Cargo.toml
- crates/cdk-redb/src/error.rs
- crates/cdk-redb/src/wallet.rs
- crates/cdk-rexie/src/wallet.rs
- crates/cdk/src/amount.rs
- crates/cdk/src/cdk_database/mod.rs
- crates/cdk/src/cdk_database/wallet_memory.rs
- crates/cdk/src/mint.rs
- crates/cdk/src/nuts/nut00.rs
- crates/cdk/src/nuts/nut04.rs
- crates/cdk/src/nuts/nut07.rs
- crates/cdk/src/nuts/nut11/mod.rs
- crates/cdk/src/nuts/nut13.rs
- crates/cdk/src/types.rs
- crates/cdk/src/util/mod.rs
- crates/cdk/src/wallet.rs
> Wallet database

- crates/cdk/src/error.rs
- crates/cdk/src/lib.rs
- crates/cdk/src/mint/error.rs
- crates/cdk/src/mint/mod.rs
- crates/cdk/src/wallet/client.rs
- crates/cdk/src/wallet/error.rs
- crates/cdk/src/wallet/mod.rs
> Error response

- crates/cdk-sqlite/src/lib.rs
- crates/cdk-sqlite/src/mint/mod.rs
- crates/cdk-sqlite/src/wallet/error.rs
- crates/cdk-sqlite/src/wallet/migration.rs
- crates/cdk-sqlite/src/wallet/mod.rs
- crates/cdk/src/cdk_database/wallet_memory.rs
> Wallet sql

- bindings/cdk-js/src/wallet.rs
- crates/cdk-cli/src/sub_commands/burn.rs
- crates/cdk/src/wallet/mod.rs
> feat: check_pending by unit

- bindings/cdk-js/src/wallet.rs
- crates/cdk-cli/src/sub_commands/mint.rs
- crates/cdk-cli/src/sub_commands/send.rs
- crates/cdk/examples/mint-token.rs
- crates/cdk/examples/p2pk.rs
- crates/cdk/src/mint/error.rs
- crates/cdk/src/mint/mod.rs
- crates/cdk/src/wallet/mod.rs
- crates/cdk/src/wallet/nostr.rs
- crates/cdk/src/wallet/util.rs
> refactor(mint): mint clean up

- bindings/cdk-js/src/nuts/nut11.rs
- bindings/cdk-js/src/nuts/nut14.rs
- crates/cdk-cli/src/sub_commands/send.rs
- crates/cdk/examples/p2pk.rs
- crates/cdk/src/mint/mod.rs
- crates/cdk/src/nuts/nut10.rs
- crates/cdk/src/nuts/nut11/mod.rs
- crates/cdk/src/nuts/nut14/mod.rs
- crates/cdk/src/wallet/mod.rs
> Public fns

- crates/cdk/src/mint/mod.rs
> feat(mint): mint_url on mint

- crates/cdk-cli/Cargo.toml
- crates/cdk-cli/src/main.rs
- crates/cdk-cli/src/sub_commands/burn.rs
- crates/cdk-cli/src/sub_commands/mint.rs
- crates/cdk-cli/src/sub_commands/mint_info.rs
- crates/cdk-cli/src/sub_commands/restore.rs
- crates/cdk-redb/src/mint.rs
- crates/cdk-redb/src/wallet.rs
- crates/cdk-sqlite/src/mint/error.rs
- crates/cdk-sqlite/src/mint/mod.rs
- crates/cdk-sqlite/src/wallet/error.rs
- crates/cdk-sqlite/src/wallet/mod.rs
> Remove unneed arg flags and use work dir

- bindings/cdk-js/src/nuts/nut06.rs
- crates/cdk/src/nuts/mod.rs
- crates/cdk/src/nuts/nut06.rs
> feat(NUT06): contact info update

- crates/cdk/src/nuts/nut00/token.rs
https://github.com/cashubtc/nuts/pull/147
> chore: token padding tests

- crates/cdk/src/wallet/mod.rs
> Wallet check proof state on error

- crates/cdk/src/nuts/nut03.rs
- crates/cdk/src/wallet/mod.rs
> feat: only increment keyset counter for derived secrets

- crates/cdk-cli/src/main.rs
> Use arg to set log level for cli

- crates/cdk/Cargo.toml
Supports trusted self-signed root certificates.
> Use native tls cert roots

- CHANGELOG.md
- crates/cdk/src/mint/error.rs
- crates/cdk/src/mint/mod.rs
- crates/cdk/src/nuts/nut11/mod.rs
> feat: sig all cannot be used in melt

- CHANGELOG.md
- crates/cdk-cli/src/sub_commands/receive.rs
> feat(cdk-cli): support nostr nsec secret keys

- CHANGELOG.md
- crates/cdk-cli/src/main.rs
- crates/cdk-cli/src/sub_commands/balance.rs
- crates/cdk-cli/src/sub_commands/burn.rs
- crates/cdk-cli/src/sub_commands/check_spent.rs
- crates/cdk-cli/src/sub_commands/melt.rs
- crates/cdk-cli/src/sub_commands/mint.rs
- crates/cdk-cli/src/sub_commands/pending_mints.rs
- crates/cdk-cli/src/sub_commands/receive.rs
- crates/cdk-cli/src/sub_commands/restore.rs
- crates/cdk-cli/src/sub_commands/send.rs
- crates/cdk-cli/src/sub_commands/update_mint_url.rs
- crates/cdk/src/wallet/mod.rs
> refactor: cdk-cli use multimint wallet

- CHANGELOG.md
- crates/cdk-redb/src/mint/mod.rs
- crates/cdk-sqlite/src/mint/mod.rs
- crates/cdk/src/cdk_database/mint_memory.rs
- crates/cdk/src/cdk_database/mod.rs
- crates/cdk/src/mint/mod.rs
> refactor: get spent and pending proofs by list of secrets or ys

- CHANGELOG.md
- crates/cdk-redb/src/wallet/mod.rs
- crates/cdk-rexie/src/wallet.rs
- crates/cdk-sqlite/src/wallet/mod.rs
- crates/cdk/src/cdk_database/mod.rs
- crates/cdk/src/cdk_database/wallet_memory.rs
- crates/cdk/src/wallet/mod.rs
> get_proofs returns Vec<ProofInfo> instead of Option<Vec<ProofInfo>>

- crates/cdk-redb/src/mint/mod.rs
- crates/cdk-sqlite/src/mint/mod.rs
- crates/cdk/src/cdk_database/mint_memory.rs
- crates/cdk/src/cdk_database/mod.rs
- crates/cdk/src/mint/mod.rs
> feat(mint): issued and redeamed by keyset

- crates/cdk/src/wallet/error.rs
- crates/cdk/src/wallet/multi_mint_wallet.rs
This should allow for better error handling for unknown wallets.
> Return WalletKey for UnknownWallet error

- crates/cdk/Cargo.toml
- crates/cdk/benches/dhke_benchmarks.rs
Add criterion benchmarks for DHKE implementation.
- Created `dhke_benchmarks.rs` in `cdk`
- Modified `Cargo.toml` to add criterion dependency and benchmark step
> Add criterion benchmarks for DHKE

- crates/cdk/src/mint/mod.rs
Refactor new mint unit test to extract mint creation helper functions.
Add rotate keyset unit test.
> Mint module: add rotate_keyset unit test

- .github/workflows/ci.yml
- Cargo.toml
- README.md
- crates/cdk-lnbits/Cargo.toml
- crates/cdk-lnbits/src/error.rs
- crates/cdk-lnbits/src/lib.rs
- crates/cdk-mintd/Cargo.toml
- crates/cdk-mintd/example.config.toml
- crates/cdk-mintd/src/config.rs
- crates/cdk-mintd/src/main.rs
- flake.lock
> feat: lnbits-rs

- bindings/cdk-js/src/nuts/nut06.rs
- crates/cdk-axum/src/router_handlers.rs
- crates/cdk-sqlite/src/wallet/migrations/20240902210905_mint_time.sql
- crates/cdk-sqlite/src/wallet/mod.rs
- crates/cdk/src/nuts/nut06.rs
implements https://github.com/cashubtc/nuts/issues/138
> feat: implement nut-06 time

- .typos.toml
- crates/cdk/src/wallet/mod.rs
> fix typos check

- crates/cdk-mintd/example.config.toml
For phoenixd, add fee_percent and reserve_fee_min
> Update example.config.toml for fees

- crates/cdk/src/wallet/multi_mint_wallet.rs
> feat: in multimint receive continue on error

- crates/cdk-axum/src/router_handlers.rs
> fix: melt verify error response

- crates/cdk/src/wallet/receive.rs
Fixes an issue where the received proofs remain in the wallet after being swapped.
> Remove received proofs from db after swap

- README.md
- crates/cdk-cli/README.md
- crates/cdk-phoenixd/README.md
> fix: typos

- crates/cdk/src/mint/melt.rs
This PR rewrites a few parts of `melt.rs` to make the code more readable.
> Minor rewrites for clarity in `mint/melt.rs`

- .github/workflows/ci.yml
- crates/cdk/Cargo.toml
- flake.nix
https://github.com/servo/rust-url/issues/992
> fix: msrv pin url

- bindings/cdk-js/src/nuts/nut06.rs
- crates/cdk-sqlite/src/wallet/migrations/20241011125207_mint_urls.sql
- crates/cdk-sqlite/src/wallet/mod.rs
- crates/cdk/src/nuts/nut06.rs
implements https://github.com/cashubtc/nuts/pull/175 for CDK
> NUT-06: add urls field

- crates/cdk-sqlite/src/mint/mod.rs
This is a minor improvement over the SQLite crate, which performs fewer SQL statements and fetches multiple results instead.
This will also remove some redundant commit() and rollback calls. Rollback already happens on drop, and there is no need for a commit if the database hasn't changed, as the transaction is used as a locking mechanism in this context.
Minor improvements to the SQLite crate to use fewer SQL statements
----
> Minor improvement in the SQLite crate

- crates/cdk-cli/src/main.rs
- crates/cdk-cli/src/sub_commands/mint.rs
- crates/cdk-cli/src/sub_commands/restore.rs
-----
Closes #484 and #485 
-----
----
> Cdk cli fixes

- Cargo.lock
- crates/cdk-integration-tests/Cargo.toml
- crates/cdk-integration-tests/src/init_regtest.rs
- crates/cdk-integration-tests/tests/regtest.rs
> chore: update regtest-rs

- DEVELOPMENT.md
> Update DEVELOPMENT.md-change discord link to Matrix link

- Cargo.lock
- crates/cdk-integration-tests/src/lib.rs
- crates/cdk-integration-tests/tests/fake_wallet.rs
- crates/cdk-integration-tests/tests/mint.rs
- crates/cdk-integration-tests/tests/regtest.rs
- crates/cdk-redb/src/mint/migrations.rs
- crates/cdk-sqlite/src/mint/migrations/20241108093102_mint_mint_quote_pubkey.sql
- crates/cdk-sqlite/src/mint/mod.rs
- crates/cdk-sqlite/src/wallet/migrations/20241108092756_wallet_mint_quote_secretkey.sql
- crates/cdk-sqlite/src/wallet/mod.rs
- crates/cdk/src/error.rs
- crates/cdk/src/mint/builder.rs
- crates/cdk/src/mint/mint_nut04.rs
- crates/cdk/src/mint/types.rs
- crates/cdk/src/nuts/mod.rs
- crates/cdk/src/nuts/nut04.rs
- crates/cdk/src/nuts/nut06.rs
- crates/cdk/src/nuts/nut20.rs
- crates/cdk/src/wallet/mint.rs
- crates/cdk/src/wallet/types.rs
- flake.lock
- flake.nix
https://github.com/cashubtc/nuts/pull/188
> feat: nut-20 signature on mint witness

- crates/cdk/examples/p2pk.rs
- Replaced unwrap() calls with proper error handling using `?` operator.
- Added comments for better code understanding.
- Managed the subscription mechanism properly to avoid potential issues with concurrent message handling.
- Ensured the main function returns a Result type for graceful error handling.
> Improve p2pk.rs

- crates/cdk/examples/mint-token.rs
- Replaced unwrap() calls with proper error handling using `?` operator.
- Added comments for better code understanding.
- Managed the subscription mechanism properly to avoid potential issues with concurrent message handling.
- Ensured the main function returns a Result type for graceful error handling.
> Improve mint-token.rs

- crates/cdk/examples/wallet.rs
- Replaced unwrap() calls with proper error handling using `?` operator.
- Added comments for better code understanding.
- Introduced a timeout mechanism to prevent infinite loops when checking the quote state.
- Ensured the main function returns a Result type for graceful error handling.
- Added descriptive comments to explain the functionality of each section in the code.
-----
-----
----
> Improve wallet example with memory store

- crates/cdk/src/mint/melt.rs
> fix: mpp melt quote msats to pay

- flake.lock
- flake.nix
- rust-toolchain.toml
> chore: update stable rust

- CHANGELOG.md
- Cargo.lock
- crates/cdk-mintd/Cargo.toml
- crates/cdk-mintd/src/env_vars.rs
- crates/cdk-mintd/src/main.rs
> feat: work_dir from env

- crates/cashu/src/lib.rs
- crates/cdk-integration-tests/src/init_fake_wallet.rs
- crates/cdk-integration-tests/src/init_regtest.rs
- crates/cdk/src/wallet/mint.rs
> refactor: mint builder in itest

- crates/cashu/src/nuts/nut05.rs
- crates/cdk/src/mint/mod.rs
- crates/cdk/src/wallet/proofs.rs
fix some comments
-----
-----
----
> chore: fix some comments

- crates/cashu/src/nuts/nut04.rs
- crates/cashu/src/nuts/nut05.rs
- crates/cdk-integration-tests/src/init_fake_wallet.rs
- crates/cdk-integration-tests/src/init_regtest.rs
- crates/cdk/src/mint/builder.rs
> fix: extra mint/melt info limits

- crates/cdk-mintd/example.config.toml
> feat: update example config

- crates/cdk-mintd/example.config.toml
- crates/cdk-mintd/src/config.rs
This PR updates `example.config.toml` such that executing locally `just final-check` works.
-----
> Fix "just final-check"

- crates/cdk-cln/Cargo.toml
- crates/cdk-cln/src/lib.rs
- crates/cdk-integration-tests/Cargo.toml
- crates/cdk-integration-tests/src/bin/regtest_mint.rs
- crates/cdk-integration-tests/src/init_mint.rs
- flake.lock
- flake.nix
> chore: update nix channel

- CHANGELOG.md
- crates/cashu/src/nuts/nut00/token.rs
- crates/cdk/src/wallet/receive.rs
> fix: multi mint check

- crates/cdk-axum/src/router_handlers.rs
- crates/cdk-integration-tests/Cargo.toml
- crates/cdk-integration-tests/src/bin/regtest_mint.rs
- crates/cdk-integration-tests/src/init_mint.rs
- crates/cdk-integration-tests/src/init_regtest.rs
- crates/cdk-integration-tests/tests/regtest.rs
- crates/cdk-lnd/src/lib.rs
- crates/cdk/src/mint/melt.rs
- misc/itests.sh
> Add LND mint to regtest itests

- .github/workflows/ci.yml
- CHANGELOG.md
- crates/cdk-integration-tests/tests/mint.rs
- crates/cdk/src/mint/keysets.rs
- crates/cdk/src/mint/mod.rs
- justfile
> Fix mint start up keyset

- CHANGELOG.md
- crates/cdk-common/Cargo.toml
- crates/cdk-common/src/error.rs
- crates/cdk-fake-wallet/src/lib.rs
- crates/cdk-integration-tests/src/init_fake_wallet.rs
- crates/cdk-integration-tests/tests/fake_wallet.rs
- crates/cdk-integration-tests/tests/regtest.rs
- crates/cdk-mintd/Cargo.toml
- crates/cdk/Cargo.toml
- crates/cdk/src/mint/melt.rs
- crates/cdk/src/mint/mint_nut04.rs
- crates/cdk/src/mint/swap.rs
- crates/cdk/src/wallet/receive.rs
- misc/fake_itests.sh
> Fix mint inflation

- flake.lock
- flake.nix
> chore: update flake

- crates/cashu/Cargo.toml
- crates/cdk-common/Cargo.toml
- crates/cdk/Cargo.toml
> chore: pin uuid

- crates/cdk-cli/src/sub_commands/mint.rs
- flake.nix
> feat: restart minting in cdk-cli with quote id

- CHANGELOG.md
- crates/cashu/Cargo.toml
- crates/cdk-axum/Cargo.toml
- crates/cdk-cli/Cargo.toml
- crates/cdk-cln/Cargo.toml
- crates/cdk-common/Cargo.toml
- crates/cdk-fake-wallet/Cargo.toml
- crates/cdk-integration-tests/Cargo.toml
- crates/cdk-lnbits/Cargo.toml
- crates/cdk-lnd/Cargo.toml
- crates/cdk-mint-rpc/Cargo.toml
- crates/cdk-mintd/Cargo.toml
- crates/cdk-phoenixd/Cargo.toml
- crates/cdk-redb/Cargo.toml
- crates/cdk-rexie/Cargo.toml
- crates/cdk-sqlite/Cargo.toml
- crates/cdk-strike/Cargo.toml
- crates/cdk/Cargo.toml
- misc/justfile.custom.just
> chore: prepare v0.7.0

- crates/cdk-common/src/error.rs
- crates/cdk-integration-tests/src/init_pure_tests.rs
- crates/cdk-integration-tests/tests/fake_wallet.rs
- crates/cdk-integration-tests/tests/mint.rs
- crates/cdk-integration-tests/tests/regtest.rs
- crates/cdk/src/mint/check_spendable.rs
- crates/cdk/src/mint/melt.rs
- crates/cdk/src/mint/mint_nut04.rs
- crates/cdk/src/mint/mod.rs
- crates/cdk/src/mint/swap.rs
- crates/cdk/src/mint/verification.rs
- flake.nix
> Refactor mint tranactions checks

- crates/cdk-integration-tests/Cargo.toml
- crates/cdk-redb/Cargo.toml
- crates/cdk-redb/src/error.rs
- crates/cdk-redb/src/mint/mod.rs
> redb update quote status use only one table open

- crates/cashu/src/nuts/nut02.rs
- crates/cdk-integration-tests/tests/fake_wallet.rs
- crates/cdk-mintd/Cargo.toml
- crates/cdk-mintd/src/config.rs
-----
closes #537 and #502
-----
----
> feat: debug print to hide seed and print version

- crates/cdk-cln/src/lib.rs
Later versions of cln-rpc introduced .call_typed which are way more ergonomic so i recommend using those instead of .call
-----
-----
----
> cdk-cln: refactor to use .call_typed

- crates/cdk/src/mint/builder.rs
> feat: custome der paths to builder

- crates/cdk-lnbits/src/error.rs
- crates/cdk-lnbits/src/lib.rs
- crates/cdk-lnd/src/error.rs
- crates/cdk-lnd/src/lib.rs
- crates/cdk-phoenixd/src/error.rs
- crates/cdk-phoenixd/src/lib.rs
- crates/cdk/src/fees.rs
> feat: use checked addition for u64

- crates/cdk-cln/src/lib.rs
- crates/cdk/src/mint/mod.rs
-----
close #554 and #506
-----
----
> fix: cln return error on stream

- CHANGELOG.md
- crates/cashu/Cargo.toml
- crates/cdk-axum/Cargo.toml
- crates/cdk-cli/Cargo.toml
- crates/cdk-cln/Cargo.toml
- crates/cdk-common/Cargo.toml
- crates/cdk-fake-wallet/Cargo.toml
- crates/cdk-lnbits/Cargo.toml
- crates/cdk-lnd/Cargo.toml
- crates/cdk-mint-rpc/Cargo.toml
- crates/cdk-mintd/Cargo.toml
- crates/cdk-phoenixd/Cargo.toml
- crates/cdk-redb/Cargo.toml
- crates/cdk-rexie/Cargo.toml
- crates/cdk-sqlite/Cargo.toml
- crates/cdk-strike/Cargo.toml
- crates/cdk/Cargo.toml
> chore: release v0.7.1

- crates/cashu/src/amount.rs
- crates/cashu/src/nuts/nut01/mod.rs
- crates/cashu/src/nuts/nut02.rs
Fixes #609
Instead write a customer serializer for Keys to serialize amounts as strings
-----
-----
----
> Drop AmountStr

- crates/cdk-sqlite/src/mint/mod.rs
- crates/cdk-sqlite/src/wallet/mod.rs
Instead, use `INSERT` and `ON CONFLICT`.  The reason is that in case of conflicts, the `REPLACE` will trigger a DELETE and then perform an INSERT, as outlined in the documentation[1], and that may cause a cascade of deletion due to our FOREIGN KEYs.
Here is the official documentation:
```
When a UNIQUE or PRIMARY KEY constraint violation occurs, the REPLACE algorithm
deletes pre-existing rows that are causing the constraint violation prior to
inserting or updating the current row and the command continues executing
normally. If a NOT NULL constraint violation occurs, the REPLACE conflict
resolution replaces the NULL value with the default value for that column, or
if the column has no default value, then the ABORT algorithm is used. If
a CHECK constraint or foreign key …
```
> Do not use `INSERT OR REPLACE` in SQLite.

- crates/cdk-integration-tests/tests/fake_wallet.rs
- crates/cdk-integration-tests/tests/mint.rs
- crates/cdk-redb/src/mint/mod.rs
- crates/cdk/src/mint/check_spendable.rs
- crates/cdk/src/mint/swap.rs
- crates/cdk/src/mint/verification.rs
> fix: attempt to swap after a failed transaction

- crates/cdk/src/mint/verification.rs
> chore: improve logging in verification

- CHANGELOG.md
> style: Clean up CHANGELOG.md formatting and consistency

- CHANGELOG.md
- crates/cdk-mintd/example.config.toml
- crates/cdk-mintd/src/config.rs
- crates/cdk-mintd/src/env_vars.rs
- crates/cdk-mintd/src/main.rs
- crates/cdk/src/mint/builder.rs
-----
follow up to https://github.com/cashubtc/cdk/pull/604
-----
----
> feat: Add tos_url to mintd config

- CHANGELOG.md
- crates/cashu/src/nuts/nut04.rs
- crates/cashu/src/nuts/nut05.rs
- crates/cdk/src/mint/melt.rs
- crates/cdk/src/mint/mint_nut04.rs
-----
For https://github.com/cashubtc/nuts/pull/235
-----
----
> Amount and unit nut04/05

- crates/cdk-mintd/src/main.rs
> refactor: remove unused ln_backends in cdk-mintd

- crates/cdk-cli/src/main.rs
- crates/cdk-cli/src/nostr_storage.rs
- crates/cdk-cli/src/sub_commands/receive.rs
- crates/cdk-common/src/database/wallet.rs
- crates/cdk-redb/src/wallet/mod.rs
- crates/cdk-sqlite/src/wallet/mod.rs
-----
closes https://github.com/cashubtc/cdk/issues/641
-----
----
> refactor: Remove nostr last checked methods from database trait

- crates/cdk/src/wallet/mint.rs
> fix: remove unnecessary clone

- .github/workflows/ci.yml
> ci: Make all jobs depend on pre-commit-checks passing

- crates/cdk-common/src/common.rs
> Get proofs conditions

- flake.nix
> chore: msrv of half

- crates/cashu/src/nuts/nut01/secret_key.rs
This PR fixes an issue that prevented CDK wallets from receiving cashu tokens that include DLEQs.
-----
In the NUTs, various fields that map to `SecretKey` are sometimes defined as `str` [^1] and sometimes as `bytes`[^2]. In the CBOR encoding (used for creating the cashu token), `bytes` is used. When encoding to JSON (in API responses from the mint), `str` is used.
Therefore, we need to be able to se-/de-serialize a `SecretKey` to/from either of these types, depending on the context. Until now, we only covered mappings to/from `String`, which means we could not receive a cashu token with DLEQ proofs, because deserialization would fail.
-----
- Wallet: Fix ability to receive cashu tokens that include DLEQ proofs
----
[^1]: For example in NUT-12, `e` and `s` in a DLEQ proof: …
> Ser/Deserialize `SecretKey` either as bytes or string

- crates/cdk-payment-processor/build.rs
Depending on the version of `protoc`, the `--experimental_allow_proto3_optional` may be needed.
-----
-----
----
> Fix protoc build error

- CHANGELOG.md
- crates/cashu/src/lib.rs
- crates/cashu/src/nuts/nut04.rs
- crates/cashu/src/nuts/nut05.rs
- crates/cdk-common/src/lib.rs
- crates/cdk-common/src/mint.rs
-----
https://github.com/cashubtc/cdk/issues/594
-----
----
> refactor: move Mint and Melt quote to cdk common

- CHANGELOG.md
- crates/cdk-sqlite/src/wallet/migrations/20250323152040_wallet_dleq_proofs.sql
- crates/cdk-sqlite/src/wallet/mod.rs
> Wallet dleq

- crates/cdk-axum/Cargo.toml
- crates/cdk-mintd/Cargo.toml
> chore: zip version

- crates/cashu/src/nuts/auth/nut22.rs
- crates/cdk/src/wallet/auth/auth_wallet.rs
> Fix dleq logging

- .github/workflows/ci.yml
- .github/workflows/docker-publish.yml
- Cargo.toml
- crates/cashu/Cargo.toml
- crates/cdk-axum/Cargo.toml
- crates/cdk-cli/Cargo.toml
- crates/cdk-cln/Cargo.toml
- crates/cdk-common/Cargo.toml
- crates/cdk-fake-wallet/Cargo.toml
- crates/cdk-integration-tests/Cargo.toml
- crates/cdk-lnbits/Cargo.toml
- crates/cdk-lnd/Cargo.toml
- crates/cdk-mint-rpc/Cargo.toml
- crates/cdk-mintd/Cargo.toml
- crates/cdk-payment-processor/Cargo.toml
- crates/cdk-redb/Cargo.toml
- crates/cdk-rexie/Cargo.toml
- crates/cdk-sqlite/Cargo.toml
- crates/cdk/Cargo.toml
- justfile
> Prepare v0.8.0

- .github/workflows/docker-publish.yml
> fix: remove arm for docker ci

- .github/workflows/ci.yml
- crates/cdk-cli/Cargo.toml
- crates/cdk-cli/src/main.rs
-----
https://github.com/cashubtc/cdk/issues/674
-----
----
> feat: Add optional redb feature flag for database support

- CHANGELOG.md
- Cargo.toml
> chore: prepare v0.8.1

- crates/cashu/src/nuts/auth/nut22.rs
- crates/cashu/src/nuts/nut00/mod.rs
- crates/cashu/src/nuts/nut03.rs
- crates/cashu/src/nuts/nut05.rs
- crates/cashu/src/nuts/nut08.rs
- crates/cdk-axum/src/router_handlers.rs
- crates/cdk-integration-tests/tests/fake_auth.rs
- crates/cdk-integration-tests/tests/fake_wallet.rs
- crates/cdk-integration-tests/tests/mint.rs
- crates/cdk-redb/src/mint/mod.rs
- crates/cdk-sqlite/src/mint/mod.rs
- crates/cdk/src/mint/melt.rs
- crates/cdk/src/mint/start_up_check.rs
- crates/cdk/src/mint/swap.rs
- crates/cdk/src/wallet/auth/auth_wallet.rs
- crates/cdk/src/wallet/melt.rs
- crates/cdk/src/wallet/proofs.rs
- crates/cdk/src/wallet/receive.rs
> Request without dleq

- .github/workflows/nutshell_itest.yml
- crates/cdk-integration-tests/tests/nutshell_wallet.rs
- flake.nix
- justfile
- misc/nutshell_wallet_itest.sh
> Nutshell wallet

- crates/cdk-cli/src/main.rs
- crates/cdk-cli/src/sub_commands/mint.rs
- crates/cdk/src/wallet/mint.rs
- crates/cdk/src/wallet/mint_connector/http_client.rs
- crates/cdk/src/wallet/multi_mint_wallet.rs
> fix: mint pending get mint info to create auth wallet

- crates/cdk/src/lib.rs
Export MintDatabase traits in the cdk crate.
-----
-----
- Export MintDatabase traits in the cdk crate
----
> Export MintDatabase traits in the cdk crate

- CHANGELOG.md
> docs: update change log

- crates/cdk/src/mint/melt.rs
> fix: amountless setting

- CHANGELOG.md
- README.md
- crates/cdk-mint-rpc/CERTIFICATES.md
- crates/cdk-mint-rpc/README.md
> docs: Add README.md for cdk-mint-rpc crate

- CHANGELOG.md
- Cargo.toml
> chore: Bump CDK crates version from 0.8.1 to 0.9.0

- crates/cdk-axum/src/lib.rs
Adds a very simple middleware layer that sticks in a CORS Header allowing from any source (this is a public API).
----
> CORS Headers in Responses

- crates/cdk-mintd/src/config.rs
> Fix debug info panic

- flake.lock
- flake.nix
- rust-toolchain.toml
> chore: update stable rust to 1.86.0

- crates/cashu/src/nuts/nut11/mod.rs
- crates/cashu/src/nuts/nut14/mod.rs
> Fix p2pk multi sig

- crates/cdk-mint-rpc/src/proto/server.rs
> fix: remove urls grpc

- Cargo.toml
> chore: bump CDK version from 0.9.0 to 0.9.1

- crates/cdk/README.md
- crates/cdk/examples/melt-token.rs
- crates/cdk/examples/mint-token.rs
- crates/cdk/examples/p2pk.rs
- crates/cdk/examples/proof-selection.rs
- crates/cdk/examples/wallet.rs
- crates/cdk/src/wallet/README.md
- crates/cdk/src/wallet/melt.rs
- crates/cdk/src/wallet/mint.rs
- crates/cdk/src/wallet/mod.rs
- crates/cdk/src/wallet/receive.rs
> feat: use tsk testmint

- crates/cdk/src/mint/start_up_check.rs
> Fix melt start up

- crates/cdk-lnd/src/lib.rs
- crates/cdk/src/mint/melt.rs
> [PATCH + BUGFIX] Multinut LND re-query and `use_mission_control`

- crates/cashu/src/nuts/nut18.rs
- crates/cdk-cli/src/sub_commands/create_request.rs
- crates/cdk-cli/src/sub_commands/pay_request.rs
-----
https://github.com/cashubtc/nuts/pull/248
-----
----
> feat: optional transport and nut10 secret on payment request

- crates/cashu/src/nuts/nut11/mod.rs
- crates/cdk-cli/src/sub_commands/send.rs
> feat: htlc from hash

- crates/cashu/src/nuts/nut07.rs
- crates/cdk/src/mint/check_spendable.rs
> fix: get spendable to return witness

- crates/cashu/src/mint_url.rs
> fix: mint url trailing slash

- crates/cashu/src/mint_url.rs
- crates/cdk-cli/src/sub_commands/create_request.rs
> chore: clippy mint_url

- crates/cashu/src/nuts/nut10.rs
- crates/cashu/src/nuts/nut18.rs
- crates/cashu/src/nuts/nut18/error.rs
- crates/cashu/src/nuts/nut18/mod.rs
- crates/cashu/src/nuts/nut18/payment_request.rs
- crates/cashu/src/nuts/nut18/secret.rs
- crates/cashu/src/nuts/nut18/transport.rs
> fix: nut18 payment request encoding/decoding

- CHANGELOG.md
- Cargo.toml
> chore: bump version to 0.9.2

- Cargo.toml
- crates/cdk-axum/Cargo.toml
- crates/cdk-axum/src/cache/backend/memory.rs
- crates/cdk-axum/src/cache/backend/redis.rs
- crates/cdk-cli/Cargo.toml
- crates/cdk-cli/src/sub_commands/create_request.rs
- crates/cdk-cli/src/sub_commands/pay_request.rs
- crates/cdk-cli/src/sub_commands/receive.rs
- crates/cdk-cln/Cargo.toml
- crates/cdk-integration-tests/tests/happy_path_mint_wallet.rs
- crates/cdk-mintd/Cargo.toml
- crates/cdk-mintd/src/lib.rs
- crates/cdk/Cargo.toml
- crates/cdk/examples/auth_wallet.rs
- crates/cdk/examples/melt-token.rs
- misc/nutshell_wallet_itest.sh
> chore: update deps

- crates/cashu/src/nuts/nut06.rs
Missing pub export.
-----
-----
- Missing pub export in NUT-06 supported settings field.
----
> Export NUT-06 supported settings field

- crates/cdk-cli/src/sub_commands/melt.rs
- crates/cdk-cli/src/sub_commands/send.rs
- crates/cdk-cli/src/utils.rs
> feat: mint url flag

- .github/workflows/ci.yml
- .github/workflows/nutshell_itest.yml
- flake.lock
- flake.nix
> chore: update flake 25.05

- README.md
- crates/cdk-axum/README.md
- crates/cdk-cln/README.md
- crates/cdk-common/README.md
- crates/cdk-fake-wallet/README.md
- crates/cdk-lnbits/README.md
- crates/cdk-lnd/README.md
- crates/cdk-mint-rpc/README.md
- crates/cdk-mintd/README.md
- crates/cdk-redb/README.md
- crates/cdk-rexie/README.md
- crates/cdk-sqlite/README.md
- crates/cdk/README.md
> chore: update readmes

- crates/cdk-mintd/src/main.rs
> fix typo in main.rs

- .github/workflows/ci.yml
- .github/workflows/nutshell_itest.yml
> chore: update ci timeout

- flake.nix
> chore: fix msrv shell

- crates/cdk-common/src/pub_sub/index.rs
- crates/cdk-mint-rpc/src/mint_rpc_cli/mod.rs
- crates/cdk/src/wallet/mint.rs
- crates/cdk/src/wallet/mod.rs
This fixes formatting issues reported by the pre commit hook with id `rustfmt`.
-----
-----
----
> refactor: fixing pre commit hooks checks

- crates/cdk/src/mint/mod.rs
> refactor: remove unused fn

- CHANGELOG.md
> chore: update changelog v0.9.3

- crates/cdk-mintd/src/main.rs
> fix: set mint version

- crates/cdk/src/pub_sub.rs
add the missing right bracket
-----
-----
----
> chore: add the missing right bracket

- .github/workflows/docker-publish-arm.yml
- .github/workflows/docker-publish.yml
> fix: prevent docker publish from overwritting other arc

- crates/cdk-cli/src/main.rs
> chore: cdk-cli version

- crates/cdk-sqlite/src/wallet/mod.rs
> fix: sqlite get_mints function

- crates/cdk-common/src/database/mint/mod.rs
- crates/cdk-redb/src/mint/mod.rs
- crates/cdk-sqlite/src/mint/memory.rs
- crates/cdk-sqlite/src/mint/mod.rs
- crates/cdk/src/mint/mod.rs
- crates/cdk/src/mint/start_up_check.rs
> Remove `melt_request`

- Cargo.toml
- crates/cdk-lnd/Cargo.toml
- crates/cdk-lnd/build.rs
- crates/cdk-lnd/src/client.rs
- crates/cdk-lnd/src/error.rs
- crates/cdk-lnd/src/lib.rs
- crates/cdk-lnd/src/proto/lnrpc.proto
- crates/cdk-lnd/src/proto/mod.rs
- crates/cdk-lnd/src/proto/routerrpc.proto
- crates/cdk-mint-rpc/Cargo.toml
- crates/cdk-mint-rpc/src/bin/mint_rpc_cli.rs
- crates/cdk-payment-processor/Cargo.toml
- crates/cdk-signatory/Cargo.toml
- crates/cdk/Cargo.toml
- crates/cdk/src/wallet/mint_connector/http_client.rs
> feat: remove fedimint tonic lnd

- crates/cashu/src/nuts/nut06.rs
- crates/cdk-cli/src/main.rs
> fix: cdk-cli create wallets for units mint supports

- crates/cdk-sqlite/src/mint/migrations.rs
- crates/cdk-sqlite/src/mint/migrations/20250626120251_rename_blind_message_y_to_b.sql
- crates/cdk-sqlite/src/mint/mod.rs
- justfile
> fix: name of blinded_message col in blind_signature

- crates/cdk-axum/src/router_handlers.rs
-----
fixes: https://github.com/cashubtc/cdk/issues/857
-----
----
> fix: mint error codes

- crates/cashu/src/nuts/nut11/mod.rs
- crates/cdk-cli/src/sub_commands/create_request.rs
- crates/cdk-cli/src/sub_commands/send.rs
> feat: refund multi sig

- CHANGELOG.md
- Cargo.toml
> chore: bump v0.11

- crates/cdk-mintd/example.config.toml
> chore: add `enabled_check_proof_state` to example.config.toml

- crates/cdk-mintd/src/main.rs
- crates/cdk/src/mint/issue/issue_nut04.rs
- crates/cdk/src/mint/start_up_check.rs
> chore: remove start up pending mint check

- crates/cdk-common/src/database/wallet.rs
- crates/cdk-redb/src/wallet/mod.rs
- crates/cdk-sqlite/src/wallet/mod.rs
- crates/cdk/src/wallet/melt/melt_bolt11.rs
- crates/cdk/src/wallet/melt/melt_bolt12.rs
- crates/cdk/src/wallet/melt/mod.rs
Expose functions to allow checking pending melt quotes.
-----
-----
- Wallet functions to check the status of pending melt quotes
----
> Wallet: Check Pending Melt Quotes

- CHANGELOG.md
- crates/cdk-integration-tests/src/init_pure_tests.rs
- crates/cdk-mintd/src/main.rs
- crates/cdk/src/mint/mod.rs
- Add background service management with graceful shutdown handling
- Refactor invoice payment monitoring to use centralized task supervision
- Update cdk-mintd and integration tests to use new lifecycle methods
- Add comprehensive documentation and lifecycle tests
-----
-----
----
> feat(cdk): add mint lifecycle management with start/stop methods

- .goosehints
- crates/cashu/src/nuts/nut03.rs
- crates/cashu/src/nuts/nut05.rs
- crates/cashu/src/nuts/nut11/mod.rs
- crates/cdk/src/mint/melt.rs
- crates/cdk/src/mint/swap.rs
> feat: sig all

- crates/cdk-common/src/wallet.rs
> TransactionId::from_hex check bytes len before copy_from_slice

- crates/cdk-axum/src/lib.rs
- crates/cdk-mintd/src/main.rs
- crates/cdk/src/mint/builder.rs
> feat(cdk): enable NUT-20 support in mint builder configuration

- crates/cdk/src/wallet/melt/melt_bolt11.rs
> chore: stop test from running

- crates/cdk-sql-common/src/mint/auth/mod.rs
- crates/cdk-sql-common/src/mint/mod.rs
- crates/cdk/src/mint/subscription/on_subscription.rs
This bug was found while adding support for postgres and writing tests #878 
-----
-----
----
> Fixed bug to avoid empty calls `get_proofs_states`

- crates/cdk-sql-common/src/mint/mod.rs
> fix: add payment method to quote

- .github/workflows/ci.yml
- misc/mintd_payment_processor.sh
> chore: free disk space on ci

- justfile
> fix: nutshell itests

- CHANGELOG.md
- Cargo.toml
- crates/cashu/src/nuts/nut04.rs
- crates/cashu/src/nuts/nut05.rs
- crates/cashu/src/nuts/nut18/payment_request.rs
- crates/cdk-cln/src/lib.rs
- crates/cdk-sql-common/src/mint/mod.rs
- crates/cdk/src/wallet/subscription/ws.rs
- flake.nix
> feat: bump msrv from 1.75.0 to 1.85.0

- .github/workflows/ci.yml
- justfile
> Reduce clippy ci and catch errors in justfile scripts

- crates/cdk-cln/src/lib.rs
- crates/cdk-integration-tests/src/cli.rs
- crates/cdk/src/mint/mod.rs
> feat: cln as msats

- flake.nix
This pr set the `NIX_PATH` as an environment variable since the `rust analyzer` needs it to function properly. 
removed 
`input 'crane' has an override for a non-existent input 'nixpkgs'` 
-----
Use nix develop .#\<dev-shell\>
-----
Rust analyzer
----
> chore(flake): add NIX_PATH for flake

- crates/cashu/src/nuts/nut18/payment_request.rs
- crates/cdk-cli/src/sub_commands/create_request.rs
- crates/cdk-cli/src/sub_commands/pay_request.rs
with a few serde directive we can get the same behaviour we had with Option<Vec<Transport>> but only using Vec<Transport>
No need to change protocol specification
-----
-----
> replace transports: Option<Vec<Transport>> with just Vec<Transport>

- crates/cdk/src/wallet/mint_connector/transport.rs
None `host_matcher` applies the proxy to all hosts, instead disabling the proxy for all hosts.
> fix: None `host_matcher` applies the proxy to all hosts

- crates/cashu/src/amount.rs
- crates/cdk/src/wallet/swap.rs
> fix: used check math

- crates/cdk-integration-tests/src/bin/start_fake_auth_mint.rs
- crates/cdk-integration-tests/src/bin/start_fake_mint.rs
- crates/cdk-integration-tests/src/bin/start_regtest_mints.rs
- crates/cdk-mintd/src/lib.rs
- crates/cdk-mintd/src/main.rs
- crates/cdk-mintd/src/setup.rs
> feat: remove unused ln_routers

- crates/cashu/src/amount.rs
This PR fixes a variable shadowing bug in the `split_with_fee` function that caused incorrect fee calculations when splitting amounts.
**The Bug:**
The function parameter `fee_ppk` (fee per thousand per keyset) was being inadvertently overwritten when calculating the total fee, causing subsequent fee calculations to use the wrong value. This resulted in exponentially higher fees than intended.
**The Fix:**
Renamed the local variable to `total_fee_ppk` to prevent shadowing the function parameter, ensuring the original fee rate remains available for correct calculations throughout the function.
**Impact:**
This bug affected wallet operations where amounts needed to be split with fees (e.g., sending 300 sats with 100 ppk fee would fail due to incorrectly calculated excessive fees).
-----
The …
> Fix Amount::split_with_fees

- crates/cdk-signatory/src/common.rs
> fix: keyset max order checked

- crates/cdk-postgres/src/lib.rs
Fixed bug with postgres reconnection in the connection pool
-----
-----
----
> Fixed bug with postgres reconnection in the connection pool

- crates/cdk-ffi/src/wallet.rs
- crates/cdk-integration-tests/Cargo.toml
- crates/cdk-integration-tests/src/init_pure_tests.rs
- crates/cdk/Cargo.toml
- crates/cdk/examples/mint-token-bolt12-with-custom-http.rs
- crates/cdk/src/bip353.rs
- crates/cdk/src/lib.rs
- crates/cdk/src/wallet/melt/melt_bip353.rs
- crates/cdk/src/wallet/melt/mod.rs
- crates/cdk/src/wallet/mint_connector/http_client.rs
- crates/cdk/src/wallet/mint_connector/mod.rs
- crates/cdk/src/wallet/mint_connector/transport.rs
Fixes #1036, #1034
-----
-----
----
> Add `resolve_dns_txt` to HttpTransport and MintConnector

- crates/cdk-cln/src/error.rs
- crates/cdk-cln/src/lib.rs
- crates/cdk-common/src/database/mint/auth/mod.rs
- crates/cdk-common/src/database/mint/mod.rs
- crates/cdk-common/src/database/mod.rs
- crates/cdk-common/src/payment.rs
- crates/cdk-integration-tests/src/init_regtest.rs
- crates/cdk-lnd/src/error.rs
- crates/cdk-lnd/src/lib.rs
- crates/cdk-mintd/src/lib.rs
- crates/cdk-mintd/src/setup.rs
- crates/cdk-payment-processor/Cargo.toml
- crates/cdk-payment-processor/src/bin/payment_processor.rs
- crates/cdk/src/mint/builder.rs
- crates/cdk/src/mint/melt.rs
- crates/cdk/src/mint/mod.rs
- crates/cdk/src/mint/proof_writer.rs
- crates/cdk/src/mint/subscription/manager.rs
- crates/cdk/src/mint/subscription/on_subscription.rs
> Store last pay index

- crates/cdk/src/mint/issue/mod.rs
> refactor: check mint request

- crates/cdk-common/src/error.rs
-----
fixes https://github.com/cashubtc/cdk/issues/1089
-----
----
> fix: error respose detail

- crates/cdk-common/src/database/mint/mod.rs
- crates/cdk-sql-common/src/mint/mod.rs
- crates/cdk/src/mint/issue/mod.rs
> feat: remove delete fns for quotes

- crates/cdk-lnbits/src/lib.rs
> fix: lnbits msats error

- README.md
> Update README with missing crates

- crates/cdk/src/wallet/subscription/ws.rs
> Fix bug with websocket close

- .github/workflows/ci.yml
> chore: update ci to fail fast

- crates/cdk-cli/src/main.rs
- crates/cdk-redb/src/error.rs
- crates/cdk-redb/src/wallet/mod.rs
- crates/cdk-sqlite/src/common.rs
- Add work directory creation check in cdk-cli main
- Add parent directory existence validation in cdk-redb wallet database
- Add parent directory check in cdk-sqlite connection manager
- Add IO error variant to cdk-redb error types for better error handling
-----
fixes https://github.com/cashubtc/cdk/issues/1160
-----
----
> fix(database): add parent directory validation before database creation

- crates/cdk-ffi/Cargo.toml
> chore: remove ctor

- Cargo.toml
- crates/cdk-cli/Cargo.toml
- crates/cdk/Cargo.toml
> chore: nostr-sdk as workspace dep
