.gitignore

after cloning the repo and executing direnv allow the git repo is dirty, because direnv is not part of .gitignore

add direnv to gitignore

---

crates/cashu/src/amount.rs
crates/cashu/src/nuts/nut00.rs
crates/cashu/src/utils.rs

There are two implementations of a split amount function that can be consolidated. The function utils::split_amount() is only used once in nut00::random() and could be replaced by Amount.split(). The only difference of the two implementations is the order in which the amounts occur, but I think this doesn't matter for the one usage in the random() function.
The tests have been moved to the amount module and adopted to the new ordering of the implementation.

consolidate split-amount

---

crates/cashu-sdk/src/wallet.rs
crates/cashu/src/error.rs

typos-cli didn't catch this one

fix: typo insufficient funds

---

flake.nix
misc/scripts/check-crates.sh
misc/scripts/check-docs.sh
misc/scripts/check-fmt.sh
misc/scripts/check.sh
misc/scripts/precommit.sh

This removes rustup from the scripts. As rust versions should be managed through the nix shell and not rust up.

Fix precommit scrips check

---

crates/cdk/src/wallet.rs

Since proofs with conditions are saved to the proofs table this simple check will work for now. In the future when melt with conditions is added this will need to be updated

fix(wallet): swap for proofs with conditons in send

---

bindings/cdk-js/src/wallet.rs
crates/cdk/src/client.rs
crates/cdk/src/wallet.rs

feat(wallet): mint and melt quote status

---

crates/cdk/src/wallet.rs

When interacting with the Wallet API, returning the total amount received after receiving a token seems helpful.

Return total received amount

---

crates/cdk/src/client.rs
crates/cdk/src/error.rs
crates/cdk/src/nuts/nut13.rs

This allows for unknown error responses to simply be returned as strings closing #121. Error response should still be more structured and improved in #121 for known common error responses.

fix: Unknown Error response error

---

bindings/cdk-js/src/lib.rs
bindings/cdk-js/src/wallet.rs
crates/cdk/src/nuts/nut00.rs
crates/cdk/src/wallet.rs

feat: check pending proofs

---

bindings/cdk-js/src/wallet.rs
crates/cdk/src/amount.rs
crates/cdk/src/nuts/nut00.rs
crates/cdk/src/nuts/nut13.rs
crates/cdk/src/util/mod.rs
crates/cdk/src/wallet.rs

Enables splitting to a target. 
Currently implemented is `SplitTarget::Value` to be used in the case where a specific amount or proofs that add up to a specific amount is desired.

Amount selection

---

README.md
bindings/cdk-js/src/wallet.rs
crates/cdk-cli/src/sub_commands/melt.rs
crates/cdk/src/nuts/mod.rs
crates/cdk/src/nuts/nut05.rs
crates/cdk/src/nuts/nut06.rs
crates/cdk/src/nuts/nut15.rs
crates/cdk/src/wallet/client.rs
crates/cdk/src/wallet/mod.rs

Simple support for MPP. This enables the implementer to use MMP payments by selecting mints and amounts themselves. This should be brought into CDK (#157)
closes #70

NUT15: Multipart Payments

---

crates/cdk/examples/proof_selection.rs

For some reason this example was minting a token worth 64 sats and attempting to generate proofs for 65 sats worth of tokens. We can either decrement the proof request to match the amount for the one ecash token or mint 1 more sat to match the proof request amount.

fix: insufficient funds bug in proof_selection example

---

CHANGELOG.md
crates/cdk/Cargo.toml
crates/cdk/src/mint/mod.rs

If an error occurs before the tokens are spent in a swap the state should be reset to unspent from pending so a wallet can try to spent again.

fix(mint): reset proofs in swap to unspent if error

---

crates/cdk/src/mint/mod.rs
crates/cdk/src/nuts/nut02.rs

First attempt to add some unit tests. I tried to start with a few fundamental operations. I hope to build up to more complex tests. This was mostly a learning exercise but I'm opening a draft PR to get some initial feedback on my approach. Is this useful? Is it redundant with existing tests? What additional assertions would be helpful?
I will probably want to move the new mint code to a helper function for use in other tests.
I think I uncovered an issue with `MintKeySet::generate_from_seed`. It requires a `MintKeysetInfo` struct, which includes an ID that is derived from the keysets but we haven't generated the keysets yet. It might be a good idea to change the function signature to accept `max_order`, `unit`, and `derivation_path` individually instead of the entire keyset info struct.

test: first mint unit tests

---

README.md
crates/cdk-rexie/README.md
crates/cdk-sqlite/Cargo.toml
crates/cdk-sqlite/README.md

* there were a copy-paste errors in README.md files of cdk-rexie and cdk-sqlite which claimed these are a redb storage backends
* Sqlite -> SQLite

fix: typos

---

crates/cdk-cln/src/error.rs
crates/cdk-redb/src/error.rs
crates/cdk-sqlite/src/mint/error.rs
crates/cdk-sqlite/src/wallet/error.rs
crates/cdk/src/nuts/nut00/mod.rs
crates/cdk/src/nuts/nut05.rs
crates/cdk/src/nuts/nut07.rs
crates/cdk/src/nuts/nut11/mod.rs
crates/cdk/src/nuts/nut12.rs
crates/cdk/src/nuts/nut14/mod.rs
crates/cdk/src/wallet/error.rs

I went through the error messages and make the capitalization consistent (only first letter of error message is in capital letters, lest is lower case - except for abbreviations such as DLEQ)

fix: make capitalization of error messages consistent

---

bindings/cdk-js/src/nuts/nut06.rs
crates/cdk-mintd/example.config.toml
crates/cdk-mintd/src/config.rs
crates/cdk-mintd/src/main.rs
crates/cdk-sqlite/src/wallet/migrations/20240902151515_icon_url.sql
crates/cdk-sqlite/src/wallet/mod.rs
crates/cdk/src/nuts/nut06.rs

as per https://github.com/cashubtc/nuts/pull/130#issuecomment-2309000463

nut06: mint_icon_url -> icon_url

---

crates/cdk/src/nuts/nut00/token.rs

This pull request adds a new test for the `try_from` function. The test checks if a `TokenV3` can be successfully converted to a `TokenV4`. The test includes a sample `TokenV3` string and asserts that the resulting `TokenV4` matches the expected value.

Add test for `TokenV4::try_from()`

---

crates/cdk-mintd/example.config.toml

For the Webhook subscription, the url under [info] must be a valid, absolute, non-local, https url

Update example.config.toml-add to strike info

---

crates/cdk/src/dhke.rs

fixes https://github.com/cashubtc/cdk/issues/322

return error in construct_proofs if arguments are not the same length

---

crates/cdk-cli/src/sub_commands/decode_token.rs
crates/cdk/Cargo.toml
crates/cdk/src/util/mod.rs

Before this PR, `decode-token` printed the pure JSON representation of a token. For V3 that is straightforward, but for V4 tokens the byte array fields were printed as arrays of numbers (decimal representation of each byte value).
<details>
<summary>Example output before PR</summary>
```
cargo run -- decode-token cashuBo2F0gqJhaUgA_9SLj17PgGFwgaNhYQFhc3hAYWNjMTI0MzVlN2I4NDg0YzNjZjE4NTAxNDkyMThhZjkwZjcxNmE1MmJmNGE1ZWQzNDdlNDhlY2MxM2Y3NzM4OGFjWCECRFODGd5IXVW-07KaZCvuWHk3WrnnpiDhHki6SCQh88-iYWlIAK0mjE0fWCZhcIKjYWECYXN4QDEzMjNkM2Q0NzA3YTU4YWQyZTIzYWRhNGU5ZjFmNDlmNWE1YjRhYzdiNzA4ZWIwZDYxZjczOGY0ODMwN2U4ZWVhY1ghAjRWqhENhLSsdHrr2Cw7AFrKUL9Ffr1XN6RBT6w659lNo2FhAWFzeEA1NmJjYmNiYjdjYzY0MDZiM2ZhNWQ1N2QyMTc0ZjRlZmY4YjQ0MDJiMTc2OTI2ZDNhNTdkM2MzZGNiYjU5ZDU3YWNYIQJzEpxXGeWZN5qXSmJjY8MzxWyvwObQGr5G1YCCgHi …
```

CLI `decode-token`: use CBOR diagnostic format instead of pure JSON

---

crates/cdk/src/amount.rs
crates/cdk/src/types.rs
crates/cdk/src/wallet/mod.rs

This allows a `Wallet` to determine the total amount paid during a melt.

Return amount and fee_paid for Melted response

---

crates/cdk/src/wallet/mod.rs

Previously, the wallet would only provide the correct change outputs to the mint if the proof total was equal to the quoted amount plus the fee reserve.
The function can now take proofs totaling more than the total quote amount.

Fix melt change amount

---

crates/cdk-cln/Cargo.toml

fixes https://github.com/cashubtc/cdk/issues/364

cdk-cln: bump cln-rpc dependency to 0.2.0

---

crates/cdk-cln/src/error.rs
crates/cdk-cln/src/lib.rs
crates/cdk-fake-wallet/src/lib.rs
crates/cdk-lnbits/src/lib.rs
crates/cdk-lnd/src/lib.rs
crates/cdk-phoenixd/src/lib.rs
crates/cdk/src/amount.rs
crates/cdk/src/cdk_lightning/mod.rs
crates/cdk/src/mint/melt.rs

In a couple of my codebases, I've found it helpful to expose the `to_unit` outside of a mint setting. Since `cdk_lightning` is behind the `mint` feature, I think moving it into the `amount` module would be beneficial so that the `mint` feature does not need to be enabled.

Refactor to_unit into amount module

---

crates/cdk-cli/src/sub_commands/balance.rs

Since mints can support different currencies, it's useful to know what kind of balance is listed with the CLI's `balance` command.

CLI `balance`: show unit when printing balances

---

.github/workflows/ci.yml

This PR fixes a few typos in the `ci.yml`, where some `build-arg` values were not separated by comma.
Without commas between the `build-args` values, the values are concatenated and treated as one.

CI yml: add missing commas in build-args list

---

crates/cdk-cli/src/main.rs
crates/cdk-cli/src/sub_commands/list_mint_proofs.rs
crates/cdk-cli/src/sub_commands/mod.rs
crates/cdk/src/amount.rs
crates/cdk/src/nuts/nut00/mod.rs
crates/cdk/src/wallet/multi_mint_wallet.rs

New command which lists proofs in wallet. Sorted buy mint and time received.
Would it be preferred to sort the proofs buy amount instead?

List proofs 

---

crates/cdk/src/amount.rs
crates/cdk/src/nuts/nut01/mod.rs
crates/cdk/src/nuts/nut02.rs

This PR brings two related changes:
- it ensures the mint keys exposed in `/v1/keys/{keyset_id}` are sorted by amount. Before, they were sorted alphabetically for the `String` representation of `Amounts` (`"123", "2", "33"` vs now `"2", "33", "123"`).
- it simplifies the first step in `Id` generation, namely the sorting of pubkeys. Before, there were two conversions (`Amount` to `String` to `u64`) before sorting, for each `PublicKey`. Now, the two conversions are skipped and the keys are directly sorted by `Amount`.

`mintd`: sort pks by amount in `/v1/keys`

---

crates/cdk-redb/src/mint/mod.rs
crates/cdk-sqlite/src/mint/mod.rs
crates/cdk/src/cdk_database/mint_memory.rs
crates/cdk/src/mint/melt.rs
crates/cdk/src/mint/swap.rs
crates/cdk/src/nuts/nut00/mod.rs
crates/cdk/src/nuts/nut00/token.rs
crates/cdk/src/types.rs
crates/cdk/src/wallet/melt.rs
crates/cdk/src/wallet/mint.rs
crates/cdk/src/wallet/mod.rs
crates/cdk/src/wallet/proofs.rs
crates/cdk/src/wallet/receive.rs
crates/cdk/src/wallet/send.rs
crates/cdk/src/wallet/swap.rs

This PR adds the `ProofsMethods` trait for `Proofs`. The goal of this trait is to have a place where such methods can be consolidated. This simplifies the codebase, makes it more readable and maintainable.
There are many operations that have to be done on a `Vec<Proof>` (a.k.a. `Proofs`), which involve iterating, mapping, and re-collecting the result. This is usually boilerplate that's repeated. One such example is summing up the amounts of all proofs involved, which this PR consolidates in `ProofsMethods::total_amount`.

Add `Proofs` trait to consolidate aggregate fns

---

crates/cdk-cli/src/sub_commands/mint_info.rs
crates/cdk/src/mint_url.rs
crates/cdk/src/nuts/nut00/mod.rs
crates/cdk/src/nuts/nut00/token.rs
crates/cdk/src/wallet/client.rs
crates/cdk/src/wallet/keysets.rs
crates/cdk/src/wallet/melt.rs
crates/cdk/src/wallet/mint.rs
crates/cdk/src/wallet/mod.rs
crates/cdk/src/wallet/proofs.rs
crates/cdk/src/wallet/receive.rs
crates/cdk/src/wallet/swap.rs

This PR simplifies how `MintUrl` is handled:
- args that represent a mint URL are given the explicit `MintUrl` type, instead of `Url` and a later `try_into` conversion
- as a consequence, `TryInto` implementations were not used anymore to convert between `MintUrl` and `Url` and were removed
- a few unused error types were also removed (in fact they were duplicated)
- the class method `join_url` was converted to a method of `MintUrl` for better readability

Simplify `MintUrl`, use it directly in `wallet/client.rs`

---

crates/cdk-cli/src/main.rs

This PR is base on issue #415 
since the Pay command is use to basically melt the token and print Payment preimage: via calling the 
` sub_commands::melt::pay(&multi_mint_wallet, sub_command_args).await`, 
it's make sense we change the COMMAND name from Pay to Melt

change cli command name from Pay to Melt

---

crates/cdk/Cargo.toml
crates/cdk/src/nuts/nut02.rs

This PR fixes an edge-case where the keyset ID could be deserialized from a string starting with a non `00` byte into a valid keyset ID with the version byte `00`.
The PR also
- replaces the custom serializer and deserializer with `serde` annotations
- adds more serialization and deserialization unit tests

Keyset ID: fix deserialization edge-case, add unit tests

---

crates/cdk-integration-tests/tests/fake_wallet.rs
crates/cdk-integration-tests/tests/regtest.rs
crates/cdk/examples/proof-selection.rs
crates/cdk/src/wallet/balance.rs
crates/cdk/src/wallet/melt.rs
crates/cdk/src/wallet/mod.rs
crates/cdk/src/wallet/multi_mint_wallet.rs
crates/cdk/src/wallet/proofs.rs
crates/cdk/src/wallet/send.rs

This PR consolidates a few similar calls.

Consolidate `Wallet::get_proofs` variants

---

crates/cdk-axum/src/lib.rs
crates/cdk-axum/src/router_handlers.rs

PR for issue #424 : change the function name to reflect route action

chore:change function name to reflect route action

---

crates/cdk-integration-tests/tests/fake_wallet.rs

Before minting the quote wait till the status of the quote is paid

fix: resolve flakey ci tests

---

crates/cdk-mintd/Cargo.toml
crates/cdk-mintd/src/config.rs
crates/cdk-mintd/src/setup.rs

PR that closed issue: #443 
added min and max delay range field to the `FakeWallet` struct, then calculate the average value inside the setup function, and pass the value in` cdk_fake_wallet::FakeWallet::new()`

Make delay time in fake wallet configurable

---

crates/cdk-axum/src/ws/subscribe.rs
crates/cdk-integration-tests/tests/regtest.rs
crates/cdk/Cargo.toml
crates/cdk/src/mint/mod.rs
crates/cdk/src/nuts/mod.rs
crates/cdk/src/nuts/nut06.rs
crates/cdk/src/nuts/nut17.rs
crates/cdk/src/nuts/nut17/mod.rs
crates/cdk/src/nuts/nut17/on_subscription.rs
crates/cdk/src/pub_sub/mod.rs

Improve #394
Make WebSocket subscriptions send the current status when subscribing. It would also be interesting to implement this logic into the PubSub crate. If we do this, this solution would be agnostic to the WebSocket, and any other bit of the rust code that wants to subscribe would inherit messages of current status when they subscribe. What are your thoughts @thesimplekid ?

Send current state of the subscriptions

---

crates/cdk/src/error.rs
crates/cdk/src/wallet/keysets.rs

PR That closes issue #422 
function `get_active_mint_keyset` to call that `get_active_mint_keysets` function and then select the keyset that should be used, the one with the lowest fee

multiple active keysets and return active keyset with lowest fee 

---

crates/cdk/src/nuts/nut02.rs
crates/cdk/src/nuts/nut13.rs

Recreating [this PR ](https://github.com/cashubtc/cdk/pull/447)without including other contributors' changes in the diff.
The existing `TryFrom<Id>` trait implementation returns a u64 but can only contain values that fit within a u32 according to the [nut13 protocol definition](https://github.com/cashubtc/nuts/blob/main/13.md#keyset-id). This PR changes the existing implementation to return a u32 and defines two new TryFrom trait implementations that can be used to convert a keyset ID to and from a u64 with no data loss.
I have also opened a PR to clarify the language in NUT13 [here](https://github.com/cashubtc/nuts/pull/189).

Update Id::try_from to return a u32 and remove redundant logic in nut13::derive_path_from_keyset_id

---

crates/cdk-mintd/src/main.rs
crates/cdk/src/error.rs
crates/cdk/src/mint/mod.rs
crates/cdk/src/mint/start_up_check.rs
flake.nix

This moves start up checks to make ensure that the stat of mint and melt quotes are up to date with the ln backend from within cdk-mint to fns on `cdk::MInt`.
-----
- cdk(mint): Added `Mint::check_pending_mint_quotes`
- cdk(mint): Added `Mint::check_pending_melt_quotes`
----

Startup checks

---

crates/cdk/src/wallet/client.rs

Store the HTTP response as a string instead of parsing it as a json::Value and cloning it several times.
This improvement has been found while working on adding WebSocket support.
* Minor improvement: avoid cloning HTTP responses; instead, store them as a string and use Serde's ability to parse strings.

Improve Http client - avoid cloning

---

crates/cdk-phoenixd/src/lib.rs

Since PHD returns a payment id after a attempting a payment this is what is used to check the state of a payment if we do not have this we cannot check and will get an error from phd. To avoid this we make sure we have an id in the right form before attempting to check if we do not the payment is in a unknown state. 
closes: https://github.com/cashubtc/cdk/issues/384
cdk-phd: Error on check if we do not have the payment id ([thesimplekid])
----

fix: check phd has valid payment id

---

crates/cdk-mintd/example.config.toml
crates/cdk-mintd/src/config.rs

when runing `cargo run --bin cdk-mintd` with fakewallet set in config.toml it gives the error
```
Finished `dev` profile [unoptimized + debuginfo] target(s) in 11.16s
Running `target/debug/cdk-mintd`
thread 'main' panicked at crates/cdk-mintd/src/main.rs:214:60:
Fake wallet defined
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
- adds the defaults for fakewallet to the sample config.toml file
- adds custom error output to assertion to assertion
```
thread 'main' panicked at crates/cdk-mintd/src/config.rs:227:38:
assertion failed: settings.fake_wallet.is_some()
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
```
thread 'main' panicked at crates/cdk-mintd/src/config.rs:219:38:
FakeWallet backend requires a valid config. …
```

fakewallet values in config

---

crates/cdk-axum/src/router_handlers.rs
crates/cdk-axum/src/ws/subscribe.rs

Avoid cloning to serialize to JSON; instead, dereference the object, as Serde needs a reference to the object.
This minor improvement was found when researching the caching layer (to propose a fix for #478)

Minor improvement cache avoid clone

---

crates/cdk-mintd/src/main.rs
crates/cdk/src/mint/builder.rs
crates/cdk/src/nuts/nut06.rs
crates/cdk/src/nuts/nut17/mod.rs

fix(mint): signal support for opt nuts

---

crates/cdk-cli/src/main.rs
crates/cdk-sqlite/src/wallet/mod.rs
crates/cdk/src/wallet/mint.rs

-----
fixes #399 
-----
cdk-sqlite: keyset counter was overwritten when keyset was fetched from mint ([thesimplekid]).
----

fix(wallet): stop sqlite from overwritting keyset counter

---

CHANGELOG.md
crates/cdk-mintd/src/main.rs
crates/cdk/src/mint/builder.rs
crates/cdk/src/nuts/mod.rs
crates/cdk/src/nuts/nut06.rs
crates/cdk/src/nuts/nut19.rs

-----
fixes: https://github.com/cashubtc/cdk/issues/491
-----
cdk: `NUT19` Settings in `NUT06` info
----

feat: nut19 settings

---

Cargo.lock
crates/cdk-cli/src/main.rs
crates/cdk-cli/src/sub_commands/mint_info.rs
crates/cdk-integration-tests/Cargo.toml
crates/cdk-integration-tests/src/lib.rs
crates/cdk-integration-tests/tests/fake_wallet.rs
crates/cdk-integration-tests/tests/integration_tests_pure.rs
crates/cdk-integration-tests/tests/regtest.rs
crates/cdk/src/nuts/nut04.rs
crates/cdk/src/nuts/nut05.rs
crates/cdk/src/wallet/client.rs
crates/cdk/src/wallet/keysets.rs
crates/cdk/src/wallet/melt.rs
crates/cdk/src/wallet/mint.rs
crates/cdk/src/wallet/mod.rs
crates/cdk/src/wallet/proofs.rs
crates/cdk/src/wallet/receive.rs
crates/cdk/src/wallet/swap.rs

This PR embeds the `mint_url` in the `HttpClient` itself, since every of its methods was anyway always with the wallet's `mint_url` as arg.
This has a few other benefits:
- it will make it easier to encapsulate logic for mints with multiple URLs inside `HttpClient` ("if URL A fails, try URL B")
- it makes "pure integration tests" possible, which can call and test mint methods without the extra HTTP layer
-----
-----
Add support for pure integration tests
----

Add support for pure integration tests

---

crates/cdk-mintd/Cargo.toml
crates/cdk-mintd/src/main.rs
crates/cdk/Cargo.toml
flake.nix

Fixes #471
-----
Compression on the mint can be tested with
```
curl -s -I -H "Accept-Encoding: zstd, br, deflate, gzip" http://localhost:8085/v1/info
```
and the console output should contain a log like
```
Request: GET /v1/info | Status: 200 OK | Compression: zstd | Duration: 289.875µs
```
Calls made by clients that don't signal support for compression
```
curl -s -I http://localhost:8085/v1/info
```
should result in
```
Request: HEAD /v1/info | Status: 200 OK | Compression: none | Duration: 552.875µs
```
To test compression on the wallet client, run in `cdk-cli`:
```
cargo run -- mint-info http://localhost:8085
```
and the mint console should again output an entry with `Compression: zstd`.
-----
- Added support for HTTP compression in wallet and mint
----

`mintd`: Add support for HTTP compression

---

.github/workflows/ci.yml
.helix/languages.toml
Cargo.lock
Dockerfile
crates/cdk-axum/Cargo.toml
crates/cdk-axum/src/cache/backend/memory.rs
crates/cdk-axum/src/cache/backend/mod.rs
crates/cdk-axum/src/cache/backend/redis.rs
crates/cdk-axum/src/cache/config.rs
crates/cdk-axum/src/cache/mod.rs
crates/cdk-axum/src/lib.rs
crates/cdk-axum/src/router_handlers.rs
crates/cdk-integration-tests/src/init_fake_wallet.rs
crates/cdk-integration-tests/src/init_regtest.rs
crates/cdk-integration-tests/src/lib.rs
crates/cdk-mintd/Cargo.toml
crates/cdk-mintd/example.config.toml
crates/cdk-mintd/src/config.rs
crates/cdk-mintd/src/env_vars.rs
crates/cdk-mintd/src/lib.rs
crates/cdk-mintd/src/main.rs
docker-compose.yaml

Fixes #478.
-----
-----
Add support for custom storages for the HTTP cache layer.
----

Introduce pluggable backend cache for the HTTP layer.

---

Cargo.lock
crates/cdk-integration-tests/tests/integration_tests_pure.rs
crates/cdk-integration-tests/tests/mint.rs
crates/cdk/Cargo.toml
crates/cdk/src/mint/config.rs
crates/cdk/src/mint/info.rs
crates/cdk/src/mint/keysets.rs
crates/cdk/src/mint/melt.rs
crates/cdk/src/mint/mint_nut04.rs
crates/cdk/src/mint/mod.rs

The main goal is to change settings without having multiple RwLock everywhere, instead having ArcSwap to update the configuration without having access to a mutable reference to the Mint.
This will allow the RPC Server, or any other medium to update the Mint without minimum contention.
This is a pre-requisite for #476
-----
-----
----

Add ArcSwap to update Mint configuration at runtime

---

Cargo.lock
crates/cdk-cli/src/sub_commands/mint.rs
crates/cdk-integration-tests/src/lib.rs
crates/cdk-integration-tests/tests/fake_wallet.rs
crates/cdk-integration-tests/tests/integration_tests_pure.rs
crates/cdk-integration-tests/tests/regtest.rs
crates/cdk/examples/mint-token.rs
crates/cdk/examples/proof-selection.rs
crates/cdk/examples/wallet.rs
crates/cdk/src/wallet/mint.rs
crates/cdk/src/wallet/multi_mint_wallet.rs
docker-compose.yaml
flake.lock

As it is currently written, it is impossible to see which proofs are returned for a mint since the total amount is returned. However, with the `ProofsMethods` trait, it is easy to calculate the total amount for the mint. This change returns the minted `Proofs` to make it possible to see which proofs are returned while not significantly decreasing the API's ergonomics. 
-----
This is a breaking change to the API.
-----
`Wallet::mint` now returns `Proofs`.
----

Return proofs for wallet mint function

---

crates/cashu/Cargo.toml
crates/cashu/src/nuts/nut02.rs
crates/cdk-cli/Cargo.toml
crates/cdk-cli/src/main.rs
crates/cdk-fake-wallet/Cargo.toml
crates/cdk-fake-wallet/src/lib.rs
crates/cdk-mintd/Cargo.toml
crates/cdk-mintd/src/setup.rs

This PR replaces direct dependencies on `rand` with re-using existing, re-exported versions of `rand`.
This makes the dependency tree smaller and avoids accidentally including multiple `rand` versions, i.e. our explicit one in addition to the existing transitive one(s).
-----
-----
* Remove direct dependencies on `rand`
----

Remove dependency on `rand`

---

crates/cdk-common/src/error.rs
crates/cdk/src/mint/melt.rs

More checks for MPP melt quotes:
- if MPP and internal (there is a mint quote for the request), error.
- if MPP but unit-method combo unsupported, error.
-----
-----
* `check_melt_request_acceptable` now an async function.
----
* [ x] I followed the [code style guidelines](https://github.com/cashubtc/cdk/blob/main/CODE_STYLE.md)
* [ x] I ran `just final-check` before committing

Further Checks on MPP Melt Quotes

---

crates/cdk-integration-tests/src/bin/regtest_mint.rs

Rename a few test variables to better separate between CLN and LND DB handles.
----

Rename vars for clarity

---

crates/cdk-integration-tests/src/init_pure_tests.rs
crates/cdk/src/mint/builder.rs
justfile

This PR
- includes the pure integration tests in `just final-check`
- fixes an edge case found by running the pure integration tests: initializing a mint with `MintMeltLimits::default()` would cause any minting and melting to fail with `AmountOutofLimitRange`. This is because the default is `min=0` and `max=0`. By removing the default, this forces the caller(s) to explicitly set the limits via `MintMeltLimits::new(min, max)`.
-----
-----
* Include pure integration tests in local check (`just final-check`)
----

Include pure integration tests in `just final-check`, fix edge-case

---

crates/cdk-integration-tests/tests/regtest.rs

fix: tests that attempt to mint before payment

---

crates/cdk/src/wallet/balance.rs

This PR addresses a few wallet TODOs that re-align `total_pending_balance` and `total_reserved_balance` to the same signature as `total_balance`.
-----
- Aligned wallet `total_pending_balance` and `total_reserved_balance` signatures
----

Align various wallet.balance() methods

---

DEVELOPMENT.md

Add a workaround on how to run the integration tests on macos
-----
-----
workaround in dev guide on how to run the integration tests on macos
----

docs(dev): add workaround for integration tests for macos

---

crates/cdk-integration-tests/Cargo.toml
crates/cdk-integration-tests/tests/fake_wallet.rs
crates/cdk/src/mint/ln.rs
crates/cdk/src/mint/mint_nut04.rs
crates/cdk/src/mint/mod.rs
crates/cdk/src/mint/start_up_check.rs
crates/cdk/src/mint/verification.rs

feat: check mint ln payment status

---

crates/cdk-mintd/src/main.rs

When a mint is started with
- a clean DB (i.e. not with a pre-existing DB from before the RPC flag was introduced in #543) and
- RPC disabled
then minting will fail with an "Unknown quote TTL" error.
This PR fixes this by setting default fallback values for the `QuoteTTL` on mint startuo, in case RPC is disabled.
-----
-----
- Fixed mint and melt error on mint initialized with RPC interface disabled
----

Fix minting and melting error on fresh `mintd` with RPC disabled

---

crates/cashu/src/nuts/nut00/mod.rs
crates/cashu/src/nuts/nut02.rs
crates/cdk-axum/src/lib.rs

The attribute `schema(as = String)` does not result in the expected behaviour.
It does not convert Id to being represented as a simple string, but rather simply rename the type `Id` to `String`.
Current openapi.json  file on master
```json
"components": {
"schemas": {
...
"BlindedMessage": {
"type": "object",
"description": "Blinded Message (also called `output`)",
"required": [
"amount",
"id",
"B_"
],
"properties": {
"amount": {
"$ref": "#/components/schemas/Amount"
},
"id": {
"$ref": "#/components/schemas/Id"
},
"B_": {
"type": "string",
"description": "Blinded secret message (B_)\n\nThe blinded secret message generated by the sender."
},
"witness": {
"allOf": [
{
"$ref": "#/components/schemas/Witness"
}
],
"nullable": true
}
}
},
...
"String": {
"type": "object",
"description": "A …
```

fix openApi attributes to keyset id to present it as a string

---

crates/cdk-cli/Cargo.toml

chore: pin base64ct as newer version is unsuported on stable

---

Cargo.toml
crates/cdk-common/src/database/mod.rs
crates/cdk-redb/Cargo.toml
crates/cdk-redb/src/mint/mod.rs
crates/cdk-sqlite/src/mint/mod.rs
crates/cdk/src/mint/check_spendable.rs

Db check on delete proofs

---

crates/cdk-integration-tests/src/init_pure_tests.rs
crates/cdk-integration-tests/tests/fake_wallet.rs
crates/cdk-integration-tests/tests/mint.rs
crates/cdk-sqlite/src/wallet/memory.rs
crates/cdk/src/mint/swap.rs

This PR slightly changes the `process_swap_request` implementation: it validates if the tx is balanced _before_ storing the new proofs in the DB. By doing this, we avoid having to later remove these proofs in case the tx is not balanced.
-----
-----
* NUT-17: Removed superfluous proof state notification
----

Simplify `process_swap_request`

---

crates/cdk-mint-rpc/src/proto/server.rs
crates/cdk-mintd/example.config.toml
crates/cdk-mintd/src/main.rs

Check tls certs exist for grpc management serve

---

crates/cdk-common/src/database/mod.rs
crates/cdk-sqlite/src/mint/error.rs
crates/cdk-sqlite/src/mint/migrations/20250306165813_keyset_id_as_foreign_key.sql
crates/cdk-sqlite/src/mint/migrations/20250307213652_keyset_id_as_foreign_key.sql
crates/cdk-sqlite/src/mint/mod.rs

feat: Add migration for keyset_id as foreign key in SQLite database

---

crates/cdk-redb/src/wallet/mod.rs
crates/cdk-rexie/src/wallet.rs
crates/cdk-sqlite/src/wallet/migrations/20250310111513_drop_nostr_last_checked.sql

#645 removed `nostr_last_checked` references from the mint storage, but the table schema and data remain.
This PR drops the table from the various storage backends:
- `cdk-sqlite`: added a migration to drop the table
- `cdk-redb`: due to a typo, the `NOSTR_LAST_CHECKED` key was pointing to the `keyset_counter` table, so no `nostr_last_checked` was ever created. Here, this PR simply removes redb references to `NOSTR_LAST_CHECKED`.
- `cdk-rexie`: bump the DB version and do not add the `NOSTR_LAST_CHECKED` object store.
-----

Drop `nostr_last_checked` table, remove references

---

crates/cdk-integration-tests/src/lib.rs

Previously, the `wait_for_mint_to_be_paid` loop used in integration tests would successfully return (`Ok`) even when the subscription ended, but the quote was not paid.
This PR fixes this edge-case.
----

Integration tests: fix `wait_for_mint_to_be_paid` loop

---

crates/cdk-integration-tests/tests/regtest.rs
crates/cdk/src/mint/melt.rs
crates/cdk/src/mint/mint_nut04.rs
crates/cdk/src/mint/verification.rs

-----
@davidcaseria  this should fix the ci issue on #596 
-----
----

fix: verification of melt quote with empty outputs

---

crates/cdk-common/src/database/mint/mod.rs
crates/cdk-common/src/database/mod.rs
crates/cdk-integration-tests/src/init_auth_mint.rs
crates/cdk-mintd/src/main.rs
crates/cdk-redb/src/mint/mod.rs
crates/cdk-sqlite/src/mint/memory.rs
crates/cdk-sqlite/src/mint/mod.rs
crates/cdk/src/mint/builder.rs
crates/cdk/src/mint/keysets/mod.rs
crates/cdk/src/mint/mod.rs
crates/cdk/src/mint/subscription/manager.rs
crates/cdk/src/mint/subscription/on_subscription.rs

This commit splits the MintDatabase trait with 30+ methods into a series of smaller traits, each dedicated to a specific subsystem of the mint service.
- MintKeysDatabase
- MintQuotesDatabase
- MintProofsDatabase
- MintSignaturesDatabase
This is the first step to splitting the Mint service into smaller, more modular, more reusable subsystems. 
No functional changes included.

split MintDatabase into separate narrower scoped traits

---

crates/cdk-mintd/example.config.toml
flake.nix
justfile
misc/justfile.custom.just

This PR removes references to `cdk-strike` and `cdk-phoenixd`.
----

Remove stale crate references

---

crates/cdk-mintd/example.config.toml

This PR removes an unused field in the `cln` section of the mint config.
----

Mint example config: remove stale `cln_path` reference

---

crates/cashu/src/nuts/nut05.rs
crates/cdk-cli/src/sub_commands/melt.rs
crates/cdk-cln/src/lib.rs
crates/cdk-common/src/common.rs
crates/cdk-common/src/error.rs
crates/cdk-common/src/payment.rs
crates/cdk-fake-wallet/src/lib.rs
crates/cdk-integration-tests/tests/regtest.rs
crates/cdk-lnbits/src/lib.rs
crates/cdk-lnd/src/lib.rs
crates/cdk-mint-rpc/src/proto/server.rs
crates/cdk-payment-processor/src/proto/mod.rs
crates/cdk-payment-processor/src/proto/payment_processor.proto
crates/cdk/src/mint/builder.rs
crates/cdk/src/mint/melt.rs
crates/cdk/src/wallet/melt.rs

-----
https://github.com/cashubtc/nuts/pull/173
closes #460 
-----
----

Melt to amountless invoice

---

crates/cdk-cli/src/sub_commands/melt.rs
crates/cdk-common/src/mint.rs
crates/cdk-payment-processor/src/proto/mod.rs
crates/cdk-payment-processor/src/proto/payment_processor.proto
crates/cdk-redb/src/mint/migrations.rs
crates/cdk-redb/src/mint/mod.rs
crates/cdk-sqlite/src/mint/migrations/20250406091754_mint_time_of_quotes.sql
crates/cdk-sqlite/src/mint/migrations/20250406093755_mint_created_time_signature.sql
crates/cdk-sqlite/src/mint/mod.rs

Time time series

---

misc/nutshell_wallet_itest.sh

Because of the nature of Rust tests, the nutshell integration test has a race condition. Triggering the issue in the local environment was hard, but it happens more often in #509 because all the keys are read from memory without blocking the database.
The error happens because, by default, Rust tests run in parallel, and maybe by design or by mistake, the external wallet did not increase its counter until the completion of the minting. This led to some tests having the same blinded messages, and the fastest test would mint successfully. The slowest test would result in the CDK failing to sign duplicated blinded messages.
In any case, the fix is on the rust side, running the tests sequentially.
-----
-----
----

Fix race condition

---

crates/cdk-integration-tests/tests/fake_wallet.rs
crates/cdk-integration-tests/tests/happy_path_mint_wallet.rs
crates/cdk-integration-tests/tests/mint.rs
crates/cdk-integration-tests/tests/nutshell_wallet.rs
crates/cdk-integration-tests/tests/regtest.rs
crates/cdk-integration-tests/tests/test_fees.rs
crates/cdk-mintd/src/config.rs
crates/cdk/src/fees.rs
crates/cdk/src/mint/mod.rs
crates/cdk/src/wallet/proofs.rs

fix #528
-----
- I have not removed `anyhow` from `cdk-integration-test/src` as these helper functions are used in the tests -> so IMO, it's better to propagate the error from these helper functions and `panic` in the tests..
- Though I also agree for directly unwraping in those helper functions that would make the code  a bit simpler..
-----
- usage of `anyhow` from tests..
----

test: use `expect` / `unwrap` instead of  `anyhow`

---

crates/cdk-signatory/Cargo.toml
crates/cdk-signatory/src/bin/cli/mod.rs

The SQLite dependency is not strictly necessary for the signatory. 
-----
-----
- Make the SQLite dependency optional for signatory
----

Make sqlite dependency optional for signatory

---

crates/cdk-mintd/example.config.toml

Updated the example configuration to disable mint_management_rpc by default. 
Additionally, updated the LN backend to use a fake wallet by default. 
This will make starting a mint with the example configuration a little bit easier
-----
-----
----

chore: disabled mint_management_rpc. update ln_backend

---

crates/cdk/src/wallet/mod.rs

Small change to remove redundant filtering of blinded messages during restore, as we already filtered for them in the code above
-----
-----
----

Remove redundant filter during restoration

---

crates/cdk/src/wallet/melt.rs
crates/cdk/src/wallet/proofs.rs

Fixes #465
This PR modifies the default `melt` operation, performing a swap to melt exact amounts instead of overpaying and getting the exchange token.
Although this may end up costing more in fees, it is more efficient sometimes since the overpaid amount is not unusable until the melt is finalized.
-----
-----
----

Perform a swap before melting by default.

---

crates/cdk/src/wallet/multi_mint_wallet.rs

A mutex is too aggressive when the shared object can be accessed read-only most of the time instead of requiring exclusive access.
-----
-----
----

Use `RwLock` instead of `Mutex`.

---

crates/cdk-sqlite/src/mint/mod.rs

noticed this during a code review for #826 
-----
-----
----

fix: add missing comma in SQL query

---

crates/cashu/src/amount.rs

Add a simple convenience method to avoid requiring the `to_unit` function import.
-----
-----
- Amount::convert_unit convenience method
----

Add Amount::convert_unit convenience method

---

crates/cdk-cli/src/sub_commands/check_pending.rs
crates/cdk-common/src/database/mint/auth/mod.rs
crates/cdk-common/src/database/mint/mod.rs
crates/cdk-common/src/database/mint/test.rs
crates/cdk-common/src/database/mod.rs
crates/cdk-integration-tests/src/init_auth_mint.rs
crates/cdk-integration-tests/src/init_pure_tests.rs
crates/cdk-integration-tests/tests/happy_path_mint_wallet.rs
crates/cdk-integration-tests/tests/mint.rs
crates/cdk-mint-rpc/src/proto/server.rs
crates/cdk-mintd/src/main.rs
crates/cdk-signatory/src/common.rs
crates/cdk-signatory/src/db_signatory.rs
crates/cdk-sqlite/src/mint/auth/mod.rs
crates/cdk-sqlite/src/mint/memory.rs
crates/cdk-sqlite/src/mint/mod.rs
crates/cdk/src/lib.rs
crates/cdk/src/mint/auth/mod.rs
crates/cdk/src/mint/check_spendable.rs
crates/cdk/src/mint/issue/issue_nut04.rs
crates/cdk/src/mint/ln.rs
crates/cdk/src/mint/melt.rs
crates/cdk/src/mint/mod.rs
crates/cdk/src/mint/proof_writer.rs
crates/cdk/src/mint/start_up_check.rs
crates/cdk/src/mint/swap.rs
crates/cdk/src/mint/verification.rs
misc/itests.sh

The transaction traits will encapsulate all database changes and also expect READ-and-lock operations to read and lock records from the database for exclusive access, thereby avoiding race conditions.
The Transaction trait expects a `rollback` operation on Drop unless the transaction has been committed. 
This PR also includes work to remove redb #787 
TODO:
-----
-----
----

Split the database trait into read and transactions.

---

Dockerfile
Dockerfile.arm

I'm getting `cdk-mintd: /lib/x86_64-linux-gnu/libc.so.6: version GLIBC_2.38 not found (required by cdk-mintd)` when running mintd 0.11.0 in docker environment
It turns out latest NixOS ships with glibc 2.38 while bookworm debian still uses glibc 2.36.
The next debian release trixie should come out soon meanwhile we may have to rely on sid version which has compatible glibc already
-----
-----
----

fix GLIBC compatibility issue

---

crates/cdk-sqlite/src/mint/error.rs
crates/cdk-sqlite/src/mint/mod.rs

do not always return UnknownQuoteTTL
return UnknownMintInfo when appropriate
add a new UnknownConfigKey for unknown key values
unit tests to cover this functionality
I encountered a misleading error message when trying to retrieve a MintInfo that did not exist from the database. I should have gotten `UnknownMintInfo` but got a `UnknownMintTTL` instead.
This PR is to fix the misleading error message.
-----
-----
----

fix: return the correct error when fetching mint config values

---

crates/cdk-fake-wallet/src/lib.rs

This pull request fixes an amount calculation in the fake wallet's incoming payment request creation.
-----
Not consistent with Bolt12 incoming payment requests. 
-----
- Fixed amount calculation in fake wallet
----

fakewallet: convert sat to msat

---

CHANGELOG.md
crates/cashu/src/nuts/nut00/mod.rs

Custom currency units were incorrectly being converted to uppercase during deserialization. This change ensures custom units maintain their original case while still allowing case-insensitive matching for standard units.
fixes: https://github.com/cashubtc/cdk/issues/908
-----
-----
----

fix(cashu): preserve original case for custom CurrencyUnit values

---

crates/cdk-cli/src/sub_commands/pay_request.rs
crates/cdk-cli/src/sub_commands/send.rs
crates/cdk-integration-tests/tests/integration_tests_pure.rs
crates/cdk-integration-tests/tests/test_fees.rs
crates/cdk/README.md
crates/cdk/examples/auth_wallet.rs
crates/cdk/examples/mint-token.rs
crates/cdk/examples/p2pk.rs
crates/cdk/examples/wallet.rs
crates/cdk/src/wallet/multi_mint_wallet.rs
crates/cdk/src/wallet/send.rs

Use `Wallet` instance in `PreparedSend` to confirm or cancel the send.
-----
-----
- Moved the logic to confirm or cancel a send from the `Wallet` to the `PreparedSend`.
----

refactor: update send functionality across wallet components

---

crates/cashu/src/nuts/nut13.rs
crates/cdk-cli/src/main.rs
crates/cdk-common/src/error.rs
crates/cdk-integration-tests/src/init_pure_tests.rs
crates/cdk-integration-tests/tests/bolt12.rs
crates/cdk-integration-tests/tests/fake_auth.rs
crates/cdk-integration-tests/tests/fake_wallet.rs
crates/cdk-integration-tests/tests/happy_path_mint_wallet.rs
crates/cdk-integration-tests/tests/regtest.rs
crates/cdk-integration-tests/tests/test_fees.rs
crates/cdk/README.md
crates/cdk/examples/auth_wallet.rs
crates/cdk/examples/melt-token.rs
crates/cdk/examples/mint-token.rs
crates/cdk/examples/p2pk.rs
crates/cdk/examples/proof-selection.rs
crates/cdk/examples/wallet.rs
crates/cdk/src/wallet/README.md
crates/cdk/src/wallet/builder.rs
crates/cdk/src/wallet/issue/issue_bolt11.rs
crates/cdk/src/wallet/issue/issue_bolt12.rs
crates/cdk/src/wallet/melt/melt_bolt11.rs
crates/cdk/src/wallet/mod.rs
crates/cdk/src/wallet/multi_mint_wallet.rs
crates/cdk/src/wallet/receive.rs
crates/cdk/src/wallet/swap.rs

The new keyset derivation uses HMAC-SHA512 instead of BIP32.
----

New Secret Derivation

---

crates/cdk-integration-tests/src/bin/start_fake_auth_mint.rs
crates/cdk-mintd/example.config.toml
crates/cdk-mintd/src/config.rs
crates/cdk-mintd/src/env_vars/auth.rs
crates/cdk-mintd/src/env_vars/mod.rs
crates/cdk-mintd/src/lib.rs

Nuts 21 and 22 allow for any endpoint to be protected with clear or blind auth. This PR adds more fine grained configurations to allow users to enable/disable auth on every endpoint and configure the auth type as clear or blind. Minting blind auth tokens always requires clear auth.
-----
I've chosen the defaults based on my experience with implementing auth in my wallet and trying to provide a smooth UX. Only minting, swapping, and restoring require blind auth. Everything else is unauthenticated. Of course, wallets should not assume these defaults, but it makes the wallet experience better if they are set in this way.
- **checkstate**: by default I do not require auth so that any wallet can easily input a token and check if its spent before prompting the user to authenticate
- **get/check …

feat: enhance auth config

---

crates/cdk/src/mint/melt.rs
crates/cdk/src/mint/proof_writer.rs

The proof_writer implicit rollback on Drop is too slow for our tests causing race conditions with Postgres.
This commit enhances the rollback logic and makes it explicit
-----
-----
----

Add explicit rollback.

---

crates/cdk-sqlite/src/common.rs

This fixes the sqlite memory exhaustion. 
-----
-----
- reduced mmap_size to prevent memory exhaustion. 
----

fix: reduce mmap_size to 5 MiB

---

crates/cdk-mintd/Cargo.toml

Building cdk-mintd with the auth feature was not enabling auth in cdk-axum, this change should pass the auth feature through
-----
-----
----

fix: pass auth cfg through mintd to axum

---

crates/cashu/Cargo.toml
crates/cashu/src/secret.rs
crates/cdk/Cargo.toml
crates/cdk/src/wallet/mod.rs
crates/cdk/src/wallet/multi_mint_wallet.rs

implement zeroize on Drop for Secret, Wallet, and MultiMintWallet
this erases sensitive memory addresses before deallocation
Minor security improvement that prevents a memory dump, swap file, or process memory inspection attack from exposing secrets left in deallocated memory addresses.
This is good hygiene and could be useful as part of a defense in depth strategy. Currently, it doesn't accomplish much because the master seed is kept in Wallet memory for the duration of the process.
A more meaningful security improvement would be to encrypt the seed on disk and load it into memory only when actively deriving keys. This would have a high performance impact due to the high frequency of ecash operations. Perhaps a better approach would be to focus on device architectures with a secure …

feat: zeroize cryptographic secrets on drop

---

crates/cashu/src/nuts/nut18/payment_request.rs
crates/cdk-integration-tests/tests/bolt12.rs
crates/cdk-integration-tests/tests/fake_auth.rs
crates/cdk-integration-tests/tests/happy_path_mint_wallet.rs
crates/cdk-integration-tests/tests/ldk_node.rs
crates/cdk-integration-tests/tests/regtest.rs
crates/cdk-integration-tests/tests/test_fees.rs
crates/cdk/Cargo.toml
crates/cdk/examples/mint-token-bolt12-with-custom-http.rs
crates/cdk/src/wallet/mint_connector/http_client.rs
crates/cdk/src/wallet/mint_connector/mod.rs
crates/cdk/src/wallet/mint_connector/transport.rs
crates/cdk/src/wallet/mod.rs

This PR allows replacing the HTTP transport layer with another library, allowing wallet ffi to provide a better-suited HTTP library that would be used instead of Reqwest.
TODO:
-  ~[ ] Implement a reqwest sync client~ Maybe another client? I think that having it as optional is good enough, the wrappers can implement their own HTTP.
> Conversely, the functionality in reqwest::blocking must not be executed within an async runtime, or it will panic when attempting to block. If calling directly from an async function, consider using an async [reqwest::Client](https://docs.rs/reqwest/latest/reqwest/struct.Client.html) instead. If the immediate context is only synchronous, but a transitive caller is async, consider changing that caller to use …

Abstract the HTTP Transport

---

crates/cdk-integration-tests/src/init_auth_mint.rs
crates/cdk-integration-tests/src/init_pure_tests.rs
crates/cdk-payment-processor/src/bin/payment_processor.rs

There was a race condition between the database storing the mint quote and the fake wallet paying the invoice of a yet non-existent mint quote
The fix was quite simple, add a delay of seconds before paying all invoices
To recreate the slow conditions that would make our database slower than the external Fakewallet in Linux
```
sudo tc qdisc add dev lo root netem delay 200ms 50ms
ionice -c3  nix develop -i -L .#stable --command just itest-payment-processor FAKEWALLET
```
To reset
```
sudo tc qdisc del dev lo root
```
-----
-----
----

Fix race conditions in minting tests

---

crates/cdk/Cargo.toml
crates/cdk/src/wallet/subscription/http.rs
crates/cdk/src/wallet/subscription/mod.rs

Makes the wallet subscriptions compatible with wasm. 
For wasm, we now use gloo timers instead of tokio intervals. 
Also, when creating the http worker for wasm we don't return a join handle because that's not a thing in wasm. Instead we break out of the loop manually.
-----
-----
----

fix: make http wallet subscriptions wasm compatible

---

crates/cdk-sql-common/build.rs
crates/cdk-sql-common/src/mint/auth/mod.rs
crates/cdk-sql-common/src/mint/mod.rs
crates/cdk-sql-common/src/wallet/mod.rs

- write generated migration files to OUT_DIR instead of source directory
- copy migration SQL files to OUT_DIR for inclusion in build artifacts
- use absolute paths from OUT_DIR in include_str! macros
- update consumer modules to include from OUT_DIR using concat! macro
these changes enable cdk to support nix sandbox builds
-----
-----
----

fix(build): use OUT_DIR for migration files

---

crates/cdk/src/wallet/multi_mint_wallet.rs

Add proper error handling and logging for add_mint operation instead of propagating errors, preventing wallet operations from failing completely when a mint cannot be added.
-----
for the mmw we don't want the wallet to fail if one mint cannot be reached. 
-----
----

fix(cdk): improve error handling when adding mint to MultiMintWallet

---

crates/cashu/src/nuts/auth/nut21.rs
crates/cdk-axum/src/router_handlers.rs
crates/cdk-integration-tests/src/bin/start_fake_auth_mint.rs
crates/cdk-mintd/src/config.rs
crates/cdk-mintd/src/env_vars/auth.rs
crates/cdk-mintd/src/lib.rs
crates/cdk/src/wallet/mint_connector/http_client.rs
crates/cdk/src/wallet/subscription/ws.rs

…nfiguration
- Add WebSocket auth token injection for client connections
- Implement server-side WebSocket authentication verification
- Add configuration options for per-endpoint WebSocket auth types
- Include comprehensive documentation and example configuration
- Support clear, blind, and no-auth modes for WebSocket endpoin
-----
-----
----

feat(cdk): add WebSocket authentication support

---

crates/cdk/src/mint/mod.rs

Internal settlement should only occur if within the same unit, otherwise settle externally.
-----
-----
----

fix: only settle same unit quote internally

---

crates/cdk/src/wallet/multi_mint_wallet.rs

Remove unnecessary mint info fetching and keyset refresh during mint addition, and improve error propagation in token restoration flow
-----
-----
----

MultiMintWallet add mints even if they are offline

---

crates/cdk-fake-wallet/src/lib.rs
crates/cdk/src/mint/melt.rs

Allows the payment processor to do currency conversion when getting the melt quote. Before, if a melt request was in a fiat unit, the `Amount::to_unit` would fail. This change moves `check_melt_request_acceptable` to after the the payment processor can tell us the amount in the requested unit.
I also added currency conversion to fake wallet using mempool's price api (https://mempool.space/api/v1/prices)
-----
-----
----

fix: handle fiat melt amount conversions

---

crates/cashu/src/nuts/nut00/token.rs
crates/cdk-ffi/src/lib.rs
crates/cdk-ffi/src/multi_mint_wallet.rs
crates/cdk-ffi/src/token.rs
crates/cdk-ffi/src/types.rs
crates/cdk-ffi/src/wallet.rs
crates/cdk-integration-tests/tests/ffi_minting_integration.rs
crates/cdk-postgres/src/lib.rs

This PR adds a lightweight API to inspect `SpendingConditions` directly from a `Token` and without requiring Mint keysets:
- New helpers on Token:
- `spending_conditions`
- `p2pk_pubkeys`
- `p2pk_refund_pubkeys`
- `htlc_hashes`
- `locktimes`
- New token_secrets() unifies V3/V4 proof traversal and removes code duplication.
- Bypasses short→long keyset-id mapping since only Secret is needed for condition parsing.
- Improves DX: external users can extract P2PK and HTLC metadata without mint context.

token: add spending-condition inspection helpers and token_secrets()

---

crates/cashu/src/nuts/nut00/mod.rs
crates/cashu/src/nuts/nut14/mod.rs

* Because of the untagged deserialization, HTLC Witness was always deserialized as P2PK Witness
* Add Preimage is more difficult to use if it always loses the signatures as it needs to be called before
Both of these are addressed, the former by deserializing HTLC Witness first as the required preimage differentiates it from a list of signatures, and the latter by copying the existing signatures if they exist.
-----
-----
----

Fix htlc witness deserialization

---

crates/cdk-common/src/wallet.rs

If you had 2 Transactions that had the same timestamp the sort could be unstable and could cause annoying issues. Now it will compare the ids if they are equal and should always have a stable sorting implementation now.
-----
Sorting `Transaction`s is now more stable
----

Make sorting Transactions a stable sort

---

crates/cdk-cli/Cargo.toml
crates/cdk-cli/src/main.rs
crates/cdk/Cargo.toml
crates/cdk/src/lib.rs
crates/cdk/src/wallet/mint_connector/http_client.rs
crates/cdk/src/wallet/mint_connector/mod.rs
crates/cdk/src/wallet/mint_connector/transport.rs
crates/cdk/src/wallet/mint_connector/transport/tor_transport.rs
crates/cdk/src/wallet/mod.rs
crates/cdk/src/wallet/multi_mint_wallet.rs

This PR introduces a Tor-backed HTTP transport implementation for the `cdk` crate under the `tor` feature.
It enables the wallet/mint connector to issue HTTP(S) requests over the Tor network using the Tor Project’s
Arti client and a Hyper 0.14-based connector.
- New module: `wallet::mint_connector::transport::tor_transport`
- New type: `TorAsync` that implements the existing `Transport` trait when the `tor` feature is enabled.
- Uses `arti-client` and `arti-hyper` (both v0.19.0), with `hyper` 0.14 and `http` 0.2 for the Tor code path.
- Bootstraps a Tor client once (lazily), reusing it across requests.
- Supports isolation tokens via Arti’s `IsolationToken`/`StreamPrefs` primitives (per-request isolation follow‑up noted below).
- Provide an optional, native Tor transport for wallet/mint …

feat: per-request tor circuits with arti

---

crates/cdk-common/src/wallet.rs
crates/cdk-ffi/src/types/transaction.rs
crates/cdk-sql-common/src/wallet/migrations/postgres/20251005120000_add_payment_info_to_transactions.sql
crates/cdk-sql-common/src/wallet/migrations/sqlite/20251005120000_add_payment_info_to_transactions.sql
crates/cdk-sql-common/src/wallet/mod.rs
crates/cdk/src/wallet/issue/issue_bolt11.rs
crates/cdk/src/wallet/issue/issue_bolt12.rs
crates/cdk/src/wallet/melt/melt_bolt11.rs
crates/cdk/src/wallet/melt/mod.rs
crates/cdk/src/wallet/receive.rs
crates/cdk/src/wallet/send.rs
crates/cdk/src/wallet/subscription/mod.rs

Add payment_request and payment_proof fields to Transaction model to store Lightning invoice details and payment preimages. Update database migrations and all transaction creation points across wallet operations (mint, melt, send, receive) to populate these fields.
closes https://github.com/cashubtc/cdk/issues/1151
-----
-----
----

feat(cdk): add payment request and proof to transaction records
